### ISSUE TITLE
can not update to 016.1

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#102]
Here is log

2021-03-01 15:03:05,014 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          migration/netshot0.xml::0.5.2_1::netshot (generated) was: 8:769910a0fe33babf3636454ed0d431d5 but is now: 8:42e0f44d320c2e000abb3082633b7c52

        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:276)
        at liquibase.Liquibase.update(Liquibase.java:198)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at onl.netfishers.netshot.Database.update(Database.java:598)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:455)
2021-03-01 15:04:40,448 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2021-03-01 15:04:52,573 WARN  [main] Netshot: Netshot is started

**Comment by SCadilhac** [comment]
What is your current version?

**Comment by myroma** [comment]
My current version 0.16.0

**Comment by SCadilhac** [comment]
As a workaround you can log into the database, and run:
```
UPDATE databasechangelog SET md5sum = '8:c9ee33cd3b985b865d875c8a5814cbd6' WHERE id = '0.5.2_1' and exectype = 'EXECUTED';
```
Then start Netshot 0.16.1.

**Comment by myroma** [comment]
Thanks
