### ISSUE TITLE
Question, Not an Issue

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#104]
Hi,

I have some Device **autodiscovery** that have been stuck in the running state in task. Is there anyway to kill those ?

Thank you again for this amazing application !

**Comment by SCadilhac** [comment]
Restarting Netshot is the only way. Do you have any log relating to this task in the main log file? I'm wondering how it happened. Is it a behavior you can reproduce?

**Comment by PatrickDenis** [comment]
So after digging a bit, i found out that these device were in the [NONAME] inventory , could log in into to devices but it is weird that they are staying in the task in running mode ? i didn't see nothing suspicious in the log file.

I have deleted the [NONAME] to see if they would disappear from the running task.

I don't want to reboot the server lol after the last time.

**Comment by PatrickDenis** [comment]
So i did rebooted  and its happening again , getting an ERR_TIME_OUT in chrome and PR_END_OF_FILE_ERROR in FireFox
i see nothing wrong in the logs.

**Comment by PatrickDenis** [comment]
Last time by importing my blank OVA or netshot and importing the DB did the trick.  So I tried to just delete de DB ( i made a backup before ) and reload the DB and sameting , wont connect. 

I'm getting : ERR_CONNECTION_REFUSED on Chrome
and : PR_END_OF_FILE_ERROR on Firefox

**Comment by PatrickDenis** [comment]
more LOGS 

2021-03-10 17:37:29,533 WARN  [main] Netshot: Netshot is started
2021-03-10 17:45:40,212 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2021-03-10 17:45:44,634 WARN  [main] DatabaseChangeLog: liquibase.statement.core.CreateSequenceStatement is not supported on mariadb, but createSequence will still execute
2021-03-10 17:45:44,758 ERROR [main] ChangeSet: Change Set migration/netshot0.xml::0.5.2_1::netshot (generated) failed.  Error: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs [Failed SQL: CREATE TABLE netshot01.device_credential_set (dtype VARCHAR(31) NOT NULL, id BIGINT AUTO_INCREMENT NOT NULL, change_date datetime NULL, name VARCHAR(255) NULL, version INT NOT NULL, community VARCHAR(255) NULL, password VARCHAR(255) NULL, super_password VARCHAR(255) NULL, username VARCHAR(255) NULL, private_key VARCHAR(10000) NULL, public_key VARCHAR(10000) NULL, mgmt_domain BIGINT NULL, CONSTRAINT PK_DEVICE_CREDENTIAL_SET PRIMARY KEY (id), UNIQUE (name))]
2021-03-10 17:45:44,762 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
liquibase.exception.MigrationFailedException: Migration failed for change set migration/netshot0.xml::0.5.2_1::netshot (generated):
     Reason: liquibase.exception.DatabaseException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs [Failed SQL: CREATE TABLE netshot01.device_credential_set (dtype VARCHAR(31) NOT NULL, id BIGINT AUTO_INCREMENT NOT NULL, change_date datetime NULL, name VARCHAR(255) NULL, version INT NOT NULL, community VARCHAR(255) NULL, password VARCHAR(255) NULL, super_password VARCHAR(255) NULL, username VARCHAR(255) NULL, private_key VARCHAR(10000) NULL, public_key VARCHAR(10000) NULL, mgmt_domain BIGINT NULL, CONSTRAINT PK_DEVICE_CREDENTIAL_SET PRIMARY KEY (id), UNIQUE (name))]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
        at liquibase.Liquibase.update(Liquibase.java:202)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at onl.netfishers.netshot.Database.update(Database.java:595)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:421)
Caused by: liquibase.exception.DatabaseException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs [Failed SQL: CREATE TABLE netshot01.device_credential_set (dtype VARCHAR(31) NOT NULL, id BIGINT AUTO_INCREMENT NOT NULL, change_date datetime NULL, name VARCHAR(255) NULL, version INT NOT NULL, community VARCHAR(255) NULL, password VARCHAR(255) NULL, super_password VARCHAR(255) NULL, username VARCHAR(255) NULL, private_key VARCHAR(10000) NULL, public_key VARCHAR(10000) NULL, mgmt_domain BIGINT NULL, CONSTRAINT PK_DEVICE_CREDENTIAL_SET PRIMARY KEY (id), UNIQUE (name))]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
        ... 6 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
        ... 11 common frames omitted
2021-03-10 17:51:07,168 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2021-03-10 17:52:10,415 WARN  [main] DeviceDriver: Skipping Netshot device driver file /usr/local/netshot/netshot.jar, because a similar driver is already loaded.
2021-03-10 17:52:10,554 WARN  [main] DeviceDriver: Skipping Netshot device driver file /usr/local/netshot/netshot.jar, because a similar driver is already loaded.
2021-03-10 17:52:10,654 WARN  [main] DeviceDriver: Skipping Netshot device driver file /usr/local/netshot/netshot.jar, because a similar driver is already loaded.
2021-03-10 17:52:10,777 WARN  [main] DeviceDriver: Skipping Netshot device driver file /usr/local/netshot/netshot.jar, because a similar driver is already loaded.
2021-03-10 17:52:10,865 WARN  [main] DeviceDriver: Skipping Netshot device driver file /usr/local/netshot/netshot.jar, because a similar driver is already loaded.
2021-03-10 17:52:10,968 WARN  [main] DeviceDriver: Skipping Netshot device driver file /usr/local/netshot/netshot.jar, because a similar driver is already loaded.
2021-03-10 17:52:11,041 WARN  [main] DeviceDriver: Skipping Netshot device driver file /usr/local/netshot/netshot.jar, because a similar driver is already loaded.
2021-03-10 17:52:11,857 WARN  [main] Netshot: Netshot is started
2021-03-10 18:06:38,167 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.

**Comment by PatrickDenis** [comment]
> What MySQL version are you using?

# mysql -V
mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
