### ISSUE TITLE
Build issues (docker and graalvm)

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#118]
Hello,

It looks like the `Dockerfile` is not working as some classes are missing (I suppose it needs to be build from a `mvn` over graalvm and not `openjdk` ?

Example of build errors

```
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/device/script/helper/JsDiagnosticHelper.java:[74,37] cannot find symbol
[ERROR]   symbol:   class Value
[ERROR]   location: class onl.netfishers.netshot.device.script.helper.JsDiagnosticHelper
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/device/script/helper/JsDiagnosticHelper.java:[109,16] cannot find symbol
[ERROR]   symbol:   class ProxyObject
[ERROR]   location: class onl.netfishers.netshot.device.script.helper.JsDiagnosticHelper
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/device/script/helper/JsConfigHelper.java:[64,37] cannot find symbol
[ERROR]   symbol:   class Value
[ERROR]   location: class onl.netfishers.netshot.device.script.helper.JsConfigHelper
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/rest/RestService.java:[169,39] package org.graalvm.polyglot.HostAccess does not exist
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/device/script/helper/PyDeviceHelper.java:[11,28] package org.graalvm.polyglot does not exist
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/device/script/helper/PyDeviceHelper.java:[12,39] package org.graalvm.polyglot.HostAccess does not exist
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/device/script/helper/PyDeviceHelper.java:[13,34] package org.graalvm.polyglot.proxy does not exist
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/device/script/helper/PyDeviceHelper.java:[14,34] package org.graalvm.polyglot.proxy does not exist
[ERROR] /opt/netshot/src/main/java/onl/netfishers/netshot/device/script/helper/PyDeviceHelper.java:[57,46] cannot find symbol
```

When building locally using graalvm, the build success randomly, most of the time it works, but sometime one unit test is randomly failing

```
[ERROR] Tests run: 48, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 73.104 s <<< FAILURE! - in onl.netfishers.netshot.ComplianceRuleTest
[ERROR] vrfRule  Time elapsed: 2.034 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: The result is not CONFORMING ==> expected: <CONFORMING> but was: <NONCONFORMING>
        at onl.netfishers.netshot.ComplianceRuleTest$PyRuleTest.vrfRule(ComplianceRuleTest.java:707)

[ERROR] vrfRule  Time elapsed: 0.043 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: The result is not CONFORMING ==> expected: <CONFORMING> but was: <NONCONFORMING>
        at onl.netfishers.netshot.ComplianceRuleTest$JsRuleTest.vrfRule(ComplianceRuleTest.java:415)

[INFO] Running onl.netfishers.netshot.NetworkAddressTest
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in onl.netfishers.netshot.NetworkAddressTest
[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ComplianceRuleTest$JsRuleTest.vrfRule:415 The result is not CONFORMING ==> expected: <CONFORMING> but was: <NONCONFORMING>
[ERROR]   ComplianceRuleTest$PyRuleTest.vrfRule:707 The result is not CONFORMING ==> expected: <CONFORMING> but was: <NONCONFORMING>
[INFO]
[ERROR] Tests run: 71, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:23 min
[INFO] Finished at: 2021-04-14T14:21:27+02:00
[INFO] ------------------------------------------------------------------------
```

Thanks

**Comment by kedare** [comment]
#119 should fix the docker build

**Comment by SCadilhac** [comment]
Thanks.

**Comment by kedare** [comment]
The random failing test is still occurring in my case (this just fixed the docker image)
Both when building in docker and building outside of docker

**Comment by SCadilhac** [comment]
Even with bf2c1ee23037428d92ff6af3fc474bf4ea13f479?

**Comment by kedare** [comment]
Indeed it looks better now :)
