### ISSUE TITLE
Affirmed Driver

### ISSUE THREAD

**Issue by achastre** [netfishers-onl/Netshot#12]
Hello,
I'm trying to create a driver for Affirmed product (I adapt cisco starOs driver because it's really close regarding the history of the companies...)

However I'm facing with a issue that  I don't understand...

You will find enclose the driver. I assume that the issue is related to my CLI declaration  ?
Below the logs
thanks again for your help ! 

Br
[Affirmed_OS.zip](https://github.com/netfishers-onl/Netshot/files/2035438/Affirmed_OS.zip)

Arnaud

Task log when i ran the snapshot : 
05] Snapshot task for device [NONAME] (10.220.0.135).
[03] Error while taking the snapshot: No regexp prompt in the selected mode. in at line number 170 at column number 41
[03] Device logs (1 next lines):
[1] Error while running function snapshot using driver affirmedOs: 'No regexp prompt in the selected mode. in at line number 170 at column number 41'.

netshot.log when I ran the snapshot:
2018-05-24 14:16:01,541 ERROR [QuartzScheduler_Worker-9] TakeSnapshotTask: Error while taking the snapshot.
javax.script.ScriptException: No regexp prompt in the selected mode. in <eval> at line number 170 at column number 41
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.DeviceDriver.cliRunFunction(DeviceDriver.java:1111)
        at onl.netfishers.netshot.device.DeviceDriver.takeSnapshot(DeviceDriver.java:1176)
        at onl.netfishers.netshot.device.DeviceDriver.runScript(DeviceDriver.java:1141)
        at onl.netfishers.netshot.device.Device.execute(Device.java:1272)
        at onl.netfishers.netshot.device.Device.takeSnapshot(Device.java:1234)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:196)
        at onl.netfishers.netshot.device.Device_$$_jvst1a_6.takeSnapshot(Device_$$_jvst1a_6.java)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:190)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:88)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jdk.nashorn.internal.runtime.ECMAException: No regexp prompt in the selected mode.
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$719$5617AA$\^eval\_._connect#command(<eval>:170)
        at jdk.nashorn.internal.scripts.Script$Recompilation$648$2255AAA$\^eval\_.snapshot(<eval>:110)
        at jdk.nashorn.internal.scripts.Script$Recompilation$717$800AAAAA$\^eval\_._connect(<eval>:375)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:647)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        ... 16 common frames omitted

**Comment by SCadilhac** [comment]
Hi Arnaud,

Your `snapshot()` function should execute `cli.macro("operate");` before running `cli.command()`.

**Comment by achastre** [comment]
Hi Sylvain,

I did call the function cli.macro("operate"); but I face now an error regarding the execution of the operate CLI macro.

I tried to change the parameters in the declaration of the CLI but it's not working.
I Assume this part is used to send the initial command to the equipement, here to pass in config mode  (as a configure in Start OS) ? 

So I modified the cmd and target to match the CLI of Affirmed : 

`operate: {
prompt: /^(\[[a-zA-Z0-9]+\][A-Za-z0-9_\-]+(?:#|>) )$/,
		pager: {
			avoid: [ "terminal length 0" ],
			match: /^---\(more( [0-9]+%)?#\)---$/,
			response: " "
		},
		macros: {
			configure: {
				cmd: "config",
				options: [ "operate", "configure" ],
				target: "config"
			}
		}
	}
`

below an example of the affirmed cli.

`PGW-LAB-01# config
Entering configuration mode terminal
PGW-LAB-01(config)# `



Error returned by netshot : 
[05] Snapshot task for device [NONAME] (10.220.0.135).
[03] Error while taking the snapshot: Error while running CLI macro 'operate' in at line number 118 at column number 4
[03] Device logs (1 next lines):
[1] Error while running function snapshot using driver affirmedOs: 'Error while running CLI macro 'operate' in at line number 118 at column number 4'.


thanks for you help

**Comment by SCadilhac** [comment]
The prompt `/^(\[[a-zA-Z0-9]+\][A-Za-z0-9_\-]+(?:#|>) )$/` for _operate_ mode doesn't seem to match the actual device prompt. You probably want to adjust it a bit: `/^[A-Za-z0-9_\-]+# $/`.

**Comment by achastre** [comment]
Hello,

I tried others expressions but without any success, until I tried this one :  /^[A-Za-z0-9_\-#]+$/.
Thanks for this part.

Now I'm facing of a timeout issue when i try to export my configuration from the device.
Do you have any idea 
```
2018-05-28 17:03:40,625 ERROR [QuartzScheduler_Worker-3] DeviceDriver: CLI I/O error.
java.io.IOException: Timeout waiting for the command output.
```

sorry to bother you that much...

**Comment by SCadilhac** [comment]
Hi @achastre, is there any paging system ("Press Enter to continue")?
Also, assuming you use version 0.8.0, in the window to start a snapshot, double-click the icon to display the debug checkbox. Check it and start a new snapshot. You should then get the debug file and see what's wrong.

**Comment by achastre** [comment]
hello @SCadilhac,
no i run the command with an option in order to avoid paging.
Unfortunatly I use the 0.7.1, I will upgrade to 0.8 correct me I'm wrong, I need to DL src code from github and then package it because there is none on your website.

**Comment by achastre** [comment]
thanks do 0.8 I managed to debug, and save the configuration. However all the configuration is not saved.
I mean that my current conf is around 6700 lines, and after the snap I only have around 890 first lines.

Sometimes the snapshot is working well (except this issue regarding the number of line) sometimes it stops with an error : 
`Error while running function snapshot using driver AffirmedOs: 'Error while waiting for a response from the device after command 'show running-config | nomore' in at line number 218 at column number 5'.`

**Comment by SCadilhac** [comment]
How long is the device taking to generate the configuration and to display it? You might want to increase the default timeout value, to let the equipment enough time to print the configuration.
`var runningConfig = cli.command("show running-config | nomore", { timeout: 60000 });`

**Comment by achastre** [comment]
Hi @SCadilhac ,
sorry for the delay.
Th output of the full configuration took me less than 5 seconds.
Increasing the timeout doesn't change anything, randomly it works and stop stopping before the end of the output, or it fails with the error below : 

`[05] Snapshot task for device PGW-Lab (10.220.0.135).
[03] Error while taking the snapshot: Error while waiting for a response from the device after command 'show running-config | nomore' in at line number 218 at column number 5
[03] Device logs (1 next lines):
[1] Error while running function snapshot using driver AffirmedOs: 'Error while waiting for a response from the device after command 'show running-config | nomore' in at line number 218 at column number 5'.`

find enclosed both debug log.

[debug_failed.log](https://github.com/netfishers-onl/Netshot/files/2061603/debug_failed.log)
[debug_success_and_not_finish.log](https://github.com/netfishers-onl/Netshot/files/2061604/debug_success_and_not_finish.log)

**Comment by SCadilhac** [comment]
I hadn't paid attention, but the prompt you mentioned, `/^[A-Za-z0-9_-#]+$/`, is not correct (it would actually match any line of one or several of the given characters).
I understand from the debug that the SSH connection starts with a logo screen. When you log in manually, do you have to press Enter or something to get to the prompt, `PGW-LAB-01#`?

**Comment by achastre** [comment]
I change the promp to `prompt: /([A-Za-z0-9_\-])+#/,`  and now it's working fine !

**Comment by SCadilhac** [comment]
Thanks for the info, glad to see it's working now!
