### ISSUE TITLE
Netshot unable to find driver

### ISSUE THREAD

**Issue by zholbrook** [netfishers-onl/Netshot#154]
I am not sure if this error is because it cannot connect to the DB or because it truly cannot find the driver. I ran this in docker and trying to use these images from docker in kubernetes, however when booting netshot I get this error.

`Starting Netshot version 0.16.3.
00:22:57.527 [main] INFO onl.netfishers.netshot.Netshot - Starting Netshot
00:22:57.529 [main] WARN onl.netfishers.netshot.Netshot - Unable to read the configuration file netshot.conf.
00:22:57.530 [main] WARN onl.netfishers.netshot.Netshot - Configuration file /etc/netshot.conf successfully read.
00:22:57.552 [main] INFO onl.netfishers.netshot.Netshot - Will go on logging to the console.
00:22:57.770 [main] ERROR onl.netfishers.netshot.database.Database - Unable to connect to the database (for the initial schema update)
java.sql.SQLException: No suitable driver found for jdbc:postgres://postgres/netshot01
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at onl.netfishers.netshot.database.Database.update(Database.java:517)
	at onl.netfishers.netshot.Netshot.main(Netshot.java:465)
2021-09-29 00:22:57,770 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
java.sql.SQLException: No suitable driver found for jdbc:postgres://postgres/netshot01
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at onl.netfishers.netshot.database.Database.update(Database.java:517)
	at onl.netfishers.netshot.Netshot.main(Netshot.java:465)
NETSHOT FATAL ERROR: Unable to connect to the database, see logs for more details
java.lang.RuntimeException: Unable to connect to the database, see logs for more details
	at onl.netfishers.netshot.database.Database.update(Database.java:527)
	at onl.netfishers.netshot.Netshot.main(Netshot.java:465)`

**Comment by SCadilhac** [comment]
It looks like it cannot find the PostgreSQL driver class indeed.

**Comment by zholbrook** [comment]
I booted up in docker and created these Images. Does it load these on boot? I’m not sure what I have done wrong here.

**Comment by zholbrook** [comment]
Jdbc driver was typed and not copied. It was not correct
