### ISSUE TITLE
netshot.jar error :( - logs from netshot.log

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#16]
Hi,

Sorry for posting again, am having the below errors..

2018-06-20 16:45:20,388 ERROR [main] DeviceDriver: Error while loading the device driver /usr/local/netshot/netshot.jar from jar file.
javax.script.ScriptException: <eval>:282:53 Expected an operand but found error
                                                var partNumber = slot.name || slot.modelName ||??"";
                                                                                               ^ in <eval> at line number 282 at column number 53
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
        at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
        at onl.netfishers.netshot.device.DeviceDriver.<init>(DeviceDriver.java:579)
        at onl.netfishers.netshot.device.DeviceDriver.refreshDrivers(DeviceDriver.java:217)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:317)
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:282:53 Expected an operand but found error
                                                var partNumber = slot.name || slot.modelName ||??"";
                                                                                               ^
        at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
        at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
        at jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:3182)
        at jdk.nashorn.internal.parser.Parser.expression(Parser.java:3325)
        at jdk.nashorn.internal.parser.Parser.assignmentExpression(Parser.java:3353)
        at jdk.nashorn.internal.parser.Parser.variableStatement(Parser.java:1088)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:884)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:863)
        at jdk.nashorn.internal.parser.Parser.statementList(Parser.java:1013)
        at jdk.nashorn.internal.parser.Parser.getBlock(Parser.java:531)
        at jdk.nashorn.internal.parser.Parser.getStatement(Parser.java:555)
        at jdk.nashorn.internal.parser.Parser.ifStatement(Parser.java:1187)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:890)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:863)
        at jdk.nashorn.internal.parser.Parser.statementList(Parser.java:1013)
        at jdk.nashorn.internal.parser.Parser.getBlock(Parser.java:531)
        at jdk.nashorn.internal.parser.Parser.getStatement(Parser.java:555)
        at jdk.nashorn.internal.parser.Parser.forStatement(Parser.java:1325)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:893)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:863)
        at jdk.nashorn.internal.parser.Parser.statementList(Parser.java:1013)
        at jdk.nashorn.internal.parser.Parser.getBlock(Parser.java:531)
        at jdk.nashorn.internal.parser.Parser.getStatement(Parser.java:555)
        at jdk.nashorn.internal.parser.Parser.ifStatement(Parser.java:1187)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:890)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:863)
        at jdk.nashorn.internal.parser.Parser.statementList(Parser.java:1013)
        at jdk.nashorn.internal.parser.Parser.getBlock(Parser.java:531)
        at jdk.nashorn.internal.parser.Parser.getStatement(Parser.java:555)
        at jdk.nashorn.internal.parser.Parser.forStatement(Parser.java:1325)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:893)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:863)
        at jdk.nashorn.internal.parser.Parser.statementList(Parser.java:1013)
        at jdk.nashorn.internal.parser.Parser.getBlock(Parser.java:531)
        at jdk.nashorn.internal.parser.Parser.tryStatement(Parser.java:1839)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:923)
        at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
        at jdk.nashorn.internal.parser.Parser.functionBody(Parser.java:2901)
        at jdk.nashorn.internal.parser.Parser.functionExpression(Parser.java:2663)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:875)
        at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
        at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
        at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
        at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
        at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
        at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
        at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
        at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
        ... 7 common frames omitted

Thanks,

**Comment by SCadilhac** [comment]
Hello,

Commit aa971cf should fix that. There was a wrong space character in the EOS driver file.
Are you running Netshot on Linux with Oracle Java? I haven't see the issue myself, that's why I'm asking.

**Comment by pizu** [comment]
Thanks for your reply.

Yes am running netshot on centos 7, latest java.
