### ISSUE TITLE
Regex-based device search in v0.17.0

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#175]
Since v0.17.0, the enable/disable feature (maybe all the calls to `PUT /api/devices/2829`) are returning a 500 (but it does enable/device the device properly)

It's trying to call a `regexp_like` function that doesn't exist in PostgreSQL, see https://stackoverflow.com/questions/14342489/error-function-regexp-likecharacter-varying-unknown-does-not-exist/14354140

Using PostgreSQL v12.6

I get the following logs:

```
2021-12-15 10:01:08,048 AAA: Request from 1.2.3.4 (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0) - mpoussin - "PUT http://xxxx/api/dev
ices/2829" - 500.                                                                                        
2021-12-15 10:01:21,126 AAA: Device 2829 (name 'xxxx.ams1', driver 'CiscoIOS12', IP address 1.2.3.4/0) has been edited.
                                                                                                         
==> /var/log/netshot/netshot.log <==                                                                     
2021-12-15 10:01:21,140 WARN  [grizzly-http-server-12] SqlExceptionHelper: SQL Error: 0, SQLState: 42883
2021-12-15 10:01:21,140 ERROR [grizzly-http-server-12] SqlExceptionHelper: ERROR: function regexp_like(character varying, character varying) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts. 
  Position: 109
2021-12-15 10:01:21,141 ERROR [grizzly-http-server-12] RestService: Uncaught exception thrown by REST service
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1613)
        at org.hibernate.query.internal.AbstractProducedQuery.uniqueResult(AbstractProducedQuery.java:1646)
        at onl.netfishers.netshot.device.DynamicDeviceGroup.refreshCache(DynamicDeviceGroup.java:174)
        at onl.netfishers.netshot.device.DynamicDeviceGroup.refreshAllGroups(DynamicDeviceGroup.java:198) 
        at onl.netfishers.netshot.rest.RestService.setDevice(RestService.java:2710)
        at jdk.internal.reflect.GeneratedMethodAccessor1188.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475) 
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:124)
        at org.glassfish.grizzly.servlet.FilterChainImpl.invokeFilterChain(FilterChainImpl.java:83)
        at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:202)
        at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:149)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:200)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:569) 
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:549)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:103)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
        at org.hibernate.loader.Loader.getResultSet(Loader.java:2297)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2050)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2012)
        at org.hibernate.loader.Loader.doQuery(Loader.java:948)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)
        at org.hibernate.loader.Loader.doList(Loader.java:2843)
        at org.hibernate.loader.Loader.doList(Loader.java:2825)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2657)
        at org.hibernate.loader.Loader.list(Loader.java:2652)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1414)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1636)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1604)
        ... 37 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: function regexp_like(character varying, character varying) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts. 
  Position: 109
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeQuery(NewProxyPreparedStatement.java:1471)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
        ... 52 common frames omitted
```

Also as small details, it looks like the `X-Forwarded-For` is not honored to get the remote IP (it's the reverse proxy IP that appears on the logs in our case)

**Comment by SCadilhac** [comment]
Indeed Netshot 0.17 has a bug where the custom Hibernate dialect is not properly loaded, which breaks the regular expression based queries.
Should be fixed with 253864a2cc22aef6263a21270803906396c10cfb
Also added X-Forwarded-For support in 70e0c66ed1f7aff9e5eac45a63660242e1bff4bd (requires related setting to be enabled in config file, for security reasons).
