### ISSUE TITLE
v0.17.0 upgrade.

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#178]
Hi,

I just upgraded to v0.17.0 and am having an issue when it's starting it's failing. logs below:

2021-12-16 13:13:31,331 INFO  [main] Netshot: Starting the Syslog server.
2021-12-16 13:13:31,331 INFO  [main] Netshot: Starting the SNMP v1/v2c trap receiver.
2021-12-16 13:13:31,346 INFO  [main] Netshot: Starting the clustering manager.
2021-12-16 13:13:31,349 INFO  [main] ClusterManager: High Availability is not enabled.
2021-12-16 13:13:31,349 INFO  [main] Netshot: Initializing the task manager.
2021-12-16 13:13:31,365 INFO  [main] StdSchedulerFactory: Using default implementation for ThreadExecutor
2021-12-16 13:13:31,375 INFO  [main] SchedulerSignalerImpl: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2021-12-16 13:13:31,375 INFO  [main] QuartzScheduler: Quartz Scheduler v.2.3.2 created.
2021-12-16 13:13:31,376 INFO  [main] RAMJobStore: RAMJobStore initialized.
2021-12-16 13:13:31,377 INFO  [main] QuartzScheduler: Scheduler meta-data: Quartz Scheduler (v2.3.2) 'NetshotMasterScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-12-16 13:13:31,377 INFO  [main] StdSchedulerFactory: Quartz scheduler 'NetshotMasterScheduler' initialized from an externally provided properties instance.
2021-12-16 13:13:31,377 INFO  [main] StdSchedulerFactory: Quartz scheduler version: 2.3.2
2021-12-16 13:13:31,377 INFO  [main] QuartzScheduler: Scheduler NetshotMasterScheduler_$_NON_CLUSTERED started.
2021-12-16 13:13:31,377 INFO  [main] StdSchedulerFactory: Using default implementation for ThreadExecutor
2021-12-16 13:13:31,379 INFO  [main] SchedulerSignalerImpl: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2021-12-16 13:13:31,379 INFO  [main] QuartzScheduler: Quartz Scheduler v.2.3.2 created.
2021-12-16 13:13:31,379 INFO  [main] RAMJobStore: RAMJobStore initialized.
2021-12-16 13:13:31,379 INFO  [main] QuartzScheduler: Scheduler meta-data: Quartz Scheduler (v2.3.2) 'NetshotRunnerScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-12-16 13:13:31,379 INFO  [main] StdSchedulerFactory: Quartz scheduler 'NetshotRunnerScheduler' initialized from an externally provided properties instance.
2021-12-16 13:13:31,379 INFO  [main] StdSchedulerFactory: Quartz scheduler version: 2.3.2
2021-12-16 13:13:31,379 INFO  [main] QuartzScheduler: Scheduler NetshotRunnerScheduler_$_NON_CLUSTERED started.
2021-12-16 13:13:31,379 INFO  [main] Netshot: Starting the REST service.
2021-12-16 13:13:31,391 INFO  [main] Netshot: Scheduling the existing tasks.
2021-12-16 13:13:31,391 INFO  [REST Service] RestService: Starting the Web/REST service thread.
2021-12-16 13:13:31,556 INFO  [REST Service] WebappContext: Starting application [GrizzlyContext] ...
2021-12-16 13:13:31,568 INFO  [REST Service] WebappContext: [GrizzlyContext] Servlet [org.glassfish.jersey.servlet.ServletContainer] registered for url pattern(s) [[/api]].
2021-12-16 13:13:31,569 INFO  [REST Service] WebappContext: Application [GrizzlyContext] is ready to service requests.  Root: [/api].
2021-12-16 13:13:31,570 WARN  [main] SqlExceptionHelper: SQL Error: 1054, SQLState: 42S22
2021-12-16 13:13:31,570 ERROR [main] SqlExceptionHelper: Unknown column 'task0_.runner_id' in 'field list'

seems that a column is missing.

Can someone help? please

Thanks.

**Comment by pizu** [comment]
![image](https://user-images.githubusercontent.com/7047326/146371031-5776a37a-d8a4-4bb4-9888-7019d50a38eb.png)

**Comment by pizu** [comment]
Hi,

I just saw this too, missed it.

2021-12-16 14:01:56,774 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2021-12-16 14:01:56,787 WARN  [main] Netshot: Logging to syslog datalog02.corporate.intra:514 has started
2021-12-16 14:01:56,789 INFO  [main] Netshot: Checking current JVM.
2021-12-16 14:01:56,790 INFO  [main] Netshot: Enabling BouncyCastle security.
2021-12-16 14:01:56,894 INFO  [main] Netshot: Updating the database schema, if necessary.
2021-12-16 14:01:58,980 INFO  [main] JdbcExecutor: SELECT COUNT(*) FROM netshot01.DATABASECHANGELOGLOCK
2021-12-16 14:01:58,984 INFO  [main] JdbcExecutor: SELECT COUNT(*) FROM netshot01.DATABASECHANGELOGLOCK
2021-12-16 14:01:58,986 INFO  [main] JdbcExecutor: SELECT `LOCKED` FROM netshot01.DATABASECHANGELOGLOCK WHERE ID=1
2021-12-16 14:01:59,001 INFO  [main] StandardLockService: Successfully acquired change log lock
2021-12-16 14:01:59,731 INFO  [main] JdbcExecutor: SELECT MD5SUM FROM netshot01.DATABASECHANGELOG WHERE MD5SUM IS NOT NULL LIMIT 1
2021-12-16 14:01:59,732 INFO  [main] JdbcExecutor: SELECT COUNT(*) FROM netshot01.DATABASECHANGELOG
2021-12-16 14:01:59,733 INFO  [main] StandardChangeLogHistoryService: Reading from netshot01.DATABASECHANGELOG
2021-12-16 14:01:59,733 INFO  [main] JdbcExecutor: SELECT * FROM netshot01.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2021-12-16 14:01:59,738 INFO  [main] StandardLockService: Successfully released change log lock
2021-12-16 14:01:59,739 ERROR [main] Database: Unable to perform initial schema update
java.lang.ClassCastException: class java.time.LocalDateTime cannot be cast to class java.lang.String (java.time.LocalDateTime and java.lang.String are in module java.base of loader 'bootstrap')
       at liquibase.changelog.StandardChangeLogHistoryService.getRanChangeSets(StandardChangeLogHistoryService.java:324)
       at liquibase.changelog.AbstractChangeLogHistoryService.upgradeChecksums(AbstractChangeLogHistoryService.java:66)
       at liquibase.changelog.StandardChangeLogHistoryService.upgradeChecksums(StandardChangeLogHistoryService.java:293)
       at liquibase.Liquibase.checkLiquibaseTables(Liquibase.java:1221)
       at liquibase.Liquibase.update(Liquibase.java:193)
       at liquibase.Liquibase.update(Liquibase.java:179)
       at onl.netfishers.netshot.database.Database.update(Database.java:226)
       at onl.netfishers.netshot.Netshot.main(Netshot.java:537)
2021-12-16 14:01:59,740 INFO  [main] Netshot: Initializing access to the database.
2021-12-16 14:01:59,804 INFO  [main] Version: HHH000412: Hibernate ORM core version [WORKING]

**Comment by SCadilhac** [comment]
What is the underlying database?
If this is MySQL/MariaDB I strongly encourage to migrate to PostgreSQL.

**Comment by pizu** [comment]
Hi,

Yes MySQL, I have everything with MySQL on this server:(

Is there anything I can do?

Will see what I can do with regards to postgresql.

Thanks

**Comment by SCadilhac** [comment]
Install PostgreSQL, create the DB (follow the install guide), change Netshot configuration to point to it, and start it once to create the tables.
Then to migrate data, you can use pgloader:
https://github.com/netfishers-onl/Netshot/wiki/MySQL-to-PostgreSQL-migration
