### ISSUE TITLE
Fortigate Snapshot Issue.

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#18]
Hi,

we are having the below issue..

When doing a backup on FortiCarrier-3800D, backup works fine,no issues, When trying to do a backup on Fortigate-1500D we are having the below issue....

2018-07-26 14:36:41,854 ERROR [QuartzScheduler_Worker-10] DeviceDriver: CLI I/O error.
onl.netfishers.netshot.device.access.Cli$WithBufferIOException: Timeout waiting for the command output.
        at onl.netfishers.netshot.device.access.Cli.readUntil(Cli.java:272)
        at onl.netfishers.netshot.device.access.Cli.send(Cli.java:299)
        at onl.netfishers.netshot.device.DeviceDriver$JsCli.send(DeviceDriver.java:773)
        at jdk.nashorn.internal.scripts.Script$Recompilation$80$6046AA$\^eval\_._connect#command(<eval>:212)
        at jdk.nashorn.internal.scripts.Script$Recompilation$35$3834AAA$\^eval\_.snapshot(<eval>:138)
        at jdk.nashorn.internal.scripts.Script$Recompilation$76$811AAAAAA$\^eval\_._connect(<eval>:417)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:649)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.DeviceDriver.cliRunFunction(DeviceDriver.java:1158)
        at onl.netfishers.netshot.device.DeviceDriver.takeSnapshot(DeviceDriver.java:1230)
        at onl.netfishers.netshot.device.DeviceDriver.runScript(DeviceDriver.java:1192)
        at onl.netfishers.netshot.device.Device.execute(Device.java:1302)
        at onl.netfishers.netshot.device.Device.takeSnapshot(Device.java:1264)
        at sun.reflect.GeneratedMethodAccessor280.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:196)
        at onl.netfishers.netshot.device.Device_$$_jvstb0c_3.takeSnapshot(Device_$$_jvstb0c_3.java)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:191)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:88)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-07-26 14:36:41,855 ERROR [QuartzScheduler_Worker-10] DeviceDriver: Error while running function snapshot using driver FortinetFortiOS.
javax.script.ScriptException: Error while waiting for a response from the device after command 'show | grep .' in <eval> at line number 218 at column number 5
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.DeviceDriver.cliRunFunction(DeviceDriver.java:1158)
        at onl.netfishers.netshot.device.DeviceDriver.takeSnapshot(DeviceDriver.java:1230)
        at onl.netfishers.netshot.device.DeviceDriver.runScript(DeviceDriver.java:1192)
        at onl.netfishers.netshot.device.Device.execute(Device.java:1302)
        at onl.netfishers.netshot.device.Device.takeSnapshot(Device.java:1264)
        at sun.reflect.GeneratedMethodAccessor280.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:196)
        at onl.netfishers.netshot.device.Device_$$_jvstb0c_3.takeSnapshot(Device_$$_jvstb0c_3.java)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:191)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:88)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jdk.nashorn.internal.runtime.ECMAException: Error while waiting for a response from the device after command 'show | grep .'
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$80$6046AA$\^eval\_._connect#command(<eval>:218)
        at jdk.nashorn.internal.scripts.Script$Recompilation$35$3834AAA$\^eval\_.snapshot(<eval>:138)
        at jdk.nashorn.internal.scripts.Script$Recompilation$76$811AAAAAA$\^eval\_._connect(<eval>:417)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:649)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        ... 15 common frames omitted
2018-07-26 14:36:41,855 ERROR [QuartzScheduler_Worker-10] TakeSnapshotTask: Error while taking the snapshot.
javax.script.ScriptException: Error while waiting for a response from the device after command 'show | grep .' in <eval> at line number 218 at column number 5
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.DeviceDriver.cliRunFunction(DeviceDriver.java:1158)
        at onl.netfishers.netshot.device.DeviceDriver.takeSnapshot(DeviceDriver.java:1230)
        at onl.netfishers.netshot.device.DeviceDriver.runScript(DeviceDriver.java:1192)
        at onl.netfishers.netshot.device.Device.execute(Device.java:1302)
        at onl.netfishers.netshot.device.Device.takeSnapshot(Device.java:1264)
        at sun.reflect.GeneratedMethodAccessor280.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:196)
        at onl.netfishers.netshot.device.Device_$$_jvstb0c_3.takeSnapshot(Device_$$_jvstb0c_3.java)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:191)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:88)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jdk.nashorn.internal.runtime.ECMAException: Error while waiting for a response from the device after command 'show | grep .'
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$80$6046AA$\^eval\_._connect#command(<eval>:218)
        at jdk.nashorn.internal.scripts.Script$Recompilation$35$3834AAA$\^eval\_.snapshot(<eval>:138)
        at jdk.nashorn.internal.scripts.Script$Recompilation$76$811AAAAAA$\^eval\_._connect(<eval>:417)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:649)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        ... 15 common frames omitted

**Comment by pizu** [comment]
Something is happening here: 

javax.script.ScriptException: Error while waiting for a response from the device after command 'show | grep .' in at line number 218 at column number 5

Don't know when it is trying to do: 

show | grep .

**Comment by SCadilhac** [comment]
`show | grep .` is used to retrieve the configuration of the FortiGate. `grep .` is a trick to bypass the pagination without altering the configuration.
In your case, either the FortiGate requires a very long time to print its configuration (the timeout is reached), or for some reason the prompt is not found after the execution of the command.
Using a 0.8.x version, you can double-click the arrow icon of the Take snapshot window and check the box to get a full debug. That should explain precisely what is happening.

**Comment by pizu** [comment]
Hi,

Thanks for your reply.

[05] Snapshot task for device [NONAME] (x.x.x.x).
[03] Error while taking the snapshot: Error while waiting for a response from the device after command 'show | grep .' in at line number 218 at column number 5
[03] Device logs (1 next lines):
[1] Error while running function snapshot using driver FortinetFortiOS: 'Error while waiting for a response from the device after command 'show | grep .' in at line number 218 at column number 5'.

**Comment by SCadilhac** [comment]
You need to enable the debug mode and download the result, to get the full details.

![image](https://user-images.githubusercontent.com/14115661/43369836-13f507de-9375-11e8-858c-78a7b38f7dbc.png)

**Comment by pizu** [comment]
Hi,

I don't have that option :(

Also after trying to do backup several times.. management got stuck and we couldn't access anymore the firewall :(

to eliminate the more issue when issuing the "show full-configuration" you can use the below:

http://www.tekhie.net/blogs/post/FortiGate-show-full-configuration-without-more

Thanks.

**Comment by SCadilhac** [comment]
To get the checkbox, assuming you run Netshot 0.8.1, just double-click the yellow arrow on the left.

The article you posted suggests to change the configuration to remove the pager before the `show full-configuration`. I don't like this, as I don't want Netshot to alter the configuration in any sort. Moreover, `show full-configuration` itself shows all the default commands and thus creates a very long configuration, that's why I prefer a simple `show` command. In any case, the `grep` part shouldn't be an issue.

**Comment by pizu** [comment]
Hi @SCadilhac with update i managed to work. - the backup took 35min.

Thanks for the help.
