### ISSUE TITLE
A language with id 'js' is not installed. Installed languages are: [llvm, python}

### ISSUE THREAD

**Issue by anburhce** [netfishers-onl/Netshot#239]
Hi team,

I am getting this error on Netshot log file.

Using : netshot 0.18.2 
postgresql-9.2.24-8
graalvm-ce-java11-linux-amd64-22.3.0
Centos 7 
====

        at onl.netfishers.netshot.Netshot.main(Netshot.java:545)
2022-11-15 14:23:45,869 ERROR [main] DeviceDriver: Error while loading the device driver /usr/local/netshot/netshot.jar from jar file.
java.lang.IllegalArgumentException: A language with id 'js' is not installed. Installed languages are: [llvm, python].
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineException.illegalArgument(PolyglotEngineException.java:131)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.throwNotInstalled(PolyglotEngineImpl.java:1101)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.requirePublicLanguage(PolyglotEngineImpl.java:1108)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.requirePublicLanguage(PolyglotContextImpl.java:1491)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.lookupLanguageContext(PolyglotContextImpl.java:1453)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:1462)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotContextDispatch.eval(PolyglotContextDispatch.java:63)
        at org.graalvm.sdk/org.graalvm.polyglot.Context.eval(Context.java:399)
        at onl.netfishers.netshot.device.DeviceDriver.getContext(DeviceDriver.java:677)
        at onl.netfishers.netshot.device.DeviceDriver.<init>(DeviceDriver.java:457)
        at onl.netfishers.netshot.device.DeviceDriver.refreshDrivers(DeviceDriver.java:345)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:545)
2022-11-15 14:23:46,530 WARN  [main] Netshot: Netshot is started

=======

So kindly help.

**Comment by anburhce** [comment]
Hi team,

I downgraded the graalvm to  graalvm-ce-java11-linux-amd64-21.3.0 it started working.

Thank you guys.
