### ISSUE TITLE
Remove running tasks

### ISSUE THREAD

**Issue by Rikharms1972** [netfishers-onl/Netshot#243]
quite often I have running tasks that are stuck.
The only way to remove them as far as I know is restarting netshot.
Is  there any way to remove these running tasks?

I added a screenshot
Thanks
![running_task_stuck](https://user-images.githubusercontent.com/59537823/207834247-30ddaabf-c773-4a68-a9a4-b099f874fa04.jpg)

**Comment by SCadilhac** [comment]
There is no way other than restarting Netshot, the actual question is what is causing these tasks to be stucj in running state? Which version are you running? Do you have any log regarding these tasks?

**Comment by Rikharms1972** [comment]
I`m running:  Netshot version 0.18.2

I don`t have any logs. How can I find logs on that particular task?

**Comment by Rikharms1972** [comment]
I will try to get the logs when it happens again

**Comment by Rikharms1972** [comment]
I have the issue now and his is what I see:
![image](https://user-images.githubusercontent.com/59537823/209126183-afd02114-6080-4654-bcb2-45dac3701041.png)

the logs show:

2022-12-21 23:13:03,621 WARN  [NetshotRunnerScheduler_Worker-8] TaskJob: Running the task 6729956 of type onl.netfishers.netshot.work.tasks.TakeSnapshotTask
2022-12-21 23:13:03,656 ERROR [NetshotRunnerScheduler_Worker-8] JobRunShell: Job RunDevice_10120.Task_6729956 threw an unhandled Exception: 
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Thread.java:798)
        at com.jcraft.jsch.Util.createSocket(Util.java:393)
        at com.jcraft.jsch.Session.connect(Session.java:217)
        at onl.netfishers.netshot.device.access.Ssh.connect(Ssh.java:329)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:253)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:205)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:212)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:95)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

**Comment by SCadilhac** [comment]
```
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
```
This kind of problem is not properly caught by the code at the moment, which causes the task to remain in running state. I will look at improving thing. But obviously the first thing to do here on your system is to avoid the lack of memory... Please check the machine RAM quantity, JVM memory settings, etc.

**Comment by Rikharms1972** [comment]
Thanks, I will do that. I also decreased the scheduled snapshots/compliance checks etc so issue is not seen anymore.
