### ISSUE TITLE
SSH to DELL X-Series doesn't work

### ISSUE THREAD

**Issue by FlorianP2023** [netfishers-onl/Netshot#264]
Hello,

I can't get the ssh login working for a DELL X1008.
The problem is, that this device starts answering with 4 LF (newline) directly after the ssh connection ist established. 
Then it prompts for User Name: and next for the Password:

***************************************************
[xxxx]$ ssh 10.145.112.120
char(10)
char(10)
char(10)
char(10)
User Name:swa
Password:***********

MAKMSD02_120#
****************************************************
This is very unusual, but the using the normal ssh login it works and it is not a problem.

But netshot generates the error below, because there is no regular regex expression for this (empty line):
[INFO] Connected using SSH to 10.145.112.120:0 using credentials DELL Switche SSH.
[ERROR] Error while running snapshot using driver DELL OS3: 'No regexp prompt in the selected mode.'.
[ERROR] Error while taking the snapshot: No regexp prompt in the selected mode.

Is there a way to overcome this? I tried different approches, but n luck, I appreciate any help or hint.
We have hundreds of these devices and would like to add them.

Regards
Florian

**Comment by FlorianP2023** [comment]
Ok. Here the CLI:
*********************
var CLI = {
	ssh: {
		macros: {
			exec: {
				options: [ "username", "password", "exec" ],
				target: "exec"
			},
			config: {
				options: [ "username", "password", "exec" ],
				target: "config"
			}
		}
	},
	username: {
		prompt: /^User Name:$/m,
		macros: {
			auto: {
				cmd: "$$NetshotUsername$$",
				options: [ "password" ]
			}
		}
	},
	password: {
		prompt: /^Password:$/,
		macros: {
			auto: {
				cmd: "$$NetshotPassword$$",
				options: [ "usernameAgain", "exec" ]
			}
		}
	},
	usernameAgain: {
		prompt: /^User Name:$/,
		fail: "Authentication failed - Telnet/SSH authentication failure."
	},
	exec: {
		prompt: /^(.+)#/,
		error: /^(Incorrect usage. .+)/m,
		pager: {
			avoid: "config paging disable",
			match: /^--More-- or \(q\)uit$/,
			response: " "
		},
		macros: {
			config: {
				cmd: "config",
				options: [ "exec", "configure" ],
				target: "config"
			},
			save: {
				cmd: "write",
				options: [ "saveConfirm", "exec" ],
				target: "exec"
			},
		}
	},
	saveConfirm: {
		prompt: /Are you sure you want to save\? \(y\/n\)/,
		macros: {
			auto: {
				cmd: "y",
				options: [ "exec" ]
			}
		}
	},
	config: {
		prompt: /^(\(.+\)) config>$/,
		error: /^(Incorrect usage. .+)/m,
		clearPrompt: true,
		macros: {
			exit: {
				cmd: "exit",
				options: [ "exec", "config" ],
				target: "exec"
			}
		}
	}
};
**********************************

And here ist the log:
**************************
[INFO] Snapshot task for device [NONAME] (10.117.112.117).
[INFO] Auto-trying SSH with credentials DELL Switche SSH.
[INFO] Connected using SSH to 10.117.112.117:0 using credentials DELL Switche SSH.
[ERROR] Error while running snapshot using driver DELL OS3: 'No regexp prompt in the selected mode.'.
[ERROR] Error while taking the snapshot: No regexp prompt in the selected mode.
******************************

And attached the putty log.
[DELL-putty.log](https://github.com/netfishers-onl/Netshot/files/12072449/DELL-putty.log)

And the last ist the full option log:
***********************************
19:54:31,956 WARN  [NetshotRunnerScheduler_Worker-3] TaskJob: Running the task 3293 of type onl.netfishers.netshot.work.tasks.TakeSnapshotTask
2023-07-17 19:54:31,963 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: Connecting to 10.117.112.118 port 22
2023-07-17 19:54:31,974 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: Connection established
2023-07-17 19:54:31,986 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: Remote version string: SSH-2.0-OpenSSH_5.9p1.RL
2023-07-17 19:54:31,986 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: Local version string: SSH-2.0-JSCH_0.2.7
2023-07-17 19:54:31,987 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: CheckCiphers: chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
2023-07-17 19:54:31,987 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: CheckMacs: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha2-512
2023-07-17 19:54:31,987 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: CheckKexes: diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: CheckSignatures: rsa-sha2-256,rsa-sha2-512,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,ssh-ed448
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: SSH_MSG_KEXINIT sent
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: SSH_MSG_KEXINIT received
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: ssh-rsa,ssh-dss
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: aes128-ctr,aes192-ctr,aes256-ctr
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: aes128-ctr,aes192-ctr,aes256-ctr
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: hmac-sha1
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: hmac-sha1
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: none
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: none
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: 
2023-07-17 19:54:32,244 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server: 
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1,ext-info-c
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: rsa-sha2-256,rsa-sha2-512,ssh-rsa,ssh-dss
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: aes128-gcm@openssh.com,aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-gcm@openssh.com,aes256-ctr,aes256-cbc
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: aes128-gcm@openssh.com,aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-gcm@openssh.com,aes256-ctr,aes256-cbc
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-512,hmac-sha1-96,hmac-md5-96
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha2-512,hmac-sha1-96,hmac-md5-96
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: none
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: none
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: 
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client: 
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: algorithm: diffie-hellman-group-exchange-sha1
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: host key algorithm: ssh-rsa
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: server->client cipher: aes128-ctr MAC: hmac-sha1 compression: none
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: kex: client->server cipher: aes128-ctr MAC: hmac-sha1 compression: none
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: SSH_MSG_KEX_DH_GEX_REQUEST(2048<3072<8192) sent
2023-07-17 19:54:32,245 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: expecting SSH_MSG_KEX_DH_GEX_GROUP
2023-07-17 19:54:32,407 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: SSH_MSG_KEX_DH_GEX_INIT sent
2023-07-17 19:54:32,407 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: expecting SSH_MSG_KEX_DH_GEX_REPLY
2023-07-17 19:54:33,524 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: ssh_rsa_verify: ssh-rsa signature true
2023-07-17 19:54:33,524 WARN  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: Permanently added '10.117.112.118' (RSA) to the list of known hosts.
2023-07-17 19:54:33,524 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: SSH_MSG_NEWKEYS sent
2023-07-17 19:54:33,534 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: SSH_MSG_NEWKEYS received
2023-07-17 19:54:33,534 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: SSH_MSG_SERVICE_REQUEST sent
2023-07-17 19:54:33,550 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: SSH_MSG_SERVICE_ACCEPT received
2023-07-17 19:54:33,623 ERROR [NetshotRunnerScheduler_Worker-3] SnapshotCliScript: Error while running snapshot using driver DELL OS3.
org.graalvm.polyglot.PolyglotException: No regexp prompt in the selected mode.
	at <js>.command(Unnamed:199)
	at <js>.snapshot(DELL_OS3_X.js:170)
	at <js>._connect(Unnamed:568)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:841)
	at onl.netfishers.netshot.device.script.SnapshotCliScript.run(SnapshotCliScript.java:90)
	at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:369)
	at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:205)
	at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:212)
	at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:96)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-07-17 19:54:33,624 INFO  [NetshotRunnerScheduler_Worker-3] Ssh$JschLogger: Disconnecting from 10.117.112.118 port 22
2023-07-17 19:54:33,624 INFO  [Connect thread 10.117.112.118 session] Ssh$JschLogger: Caught an exception, leaving main loop due to Socket closed
2023-07-17 19:54:33,624 ERROR [NetshotRunnerScheduler_Worker-3] TakeSnapshotTask: Task 3293. Error while taking the snapshot.
org.graalvm.polyglot.PolyglotException: No regexp prompt in the selected mode.
	at <js>.command(Unnamed:199)
	at <js>.snapshot(DELL_OS3_X.js:170)
	at <js>._connect(Unnamed:568)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:841)
	at onl.netfishers.netshot.device.script.SnapshotCliScript.run(SnapshotCliScript.java:90)
	at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:369)
	at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:205)
	at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:212)
	at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:96)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2023-07-17 19:54:33,636 WARN  [NetshotRunnerScheduler_Worker-3] TaskJob: End of task 3293.
***************************

Anything else you need?
Thanks for looking into.

**Comment by SCadilhac** [comment]
Do you have `cli.macro("exec");` at the beginning of your `snapshot` function?
You can also collect full snapshot dump (https://github.com/netfishers-onl/Netshot/wiki/Snapshot-troubleshooting).

**Comment by FlorianP2023** [comment]
Shame on me ....

I copied my driver from another DELL driver I wrote before and forgot to change the first line ...
Thank you very much for your help and support. Now it works and the driver can establish a connection.

Solved!
