### ISSUE TITLE
Cisco NX-OS v0.19.0 - error

### ISSUE THREAD

**Issue by pfunkylol** [netfishers-onl/Netshot#272]
Hello,

While trying to backup NXOS device, the following error is presented in the logs after the upgrade to v0.19.0

ERROR [NetshotRunnerScheduler_Worker-1] SnapshotCliScript: Error while running snapshot using driver CiscoNXOS.
org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (debug) on onl.netfishers.netshot.device.script.CliScript$1 failed due to: Unknown identifier: debug
        at <js>.debug(Unnamed:440)
        at <js>.snapshot(Cisco_NX-OS.js:304)
        at <js>._connect(Unnamed:701)
        at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:881)
        at onl.netfishers.netshot.device.script.SnapshotCliScript.run(SnapshotCliScript.java:88)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:250)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:196)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:218)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:94)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)

The following commit [6f5a7d6](https://github.com/netfishers-onl/Netshot/commit/6f5a7d646a489f4cf583437a6de9b2fb2cf9af4f) should be available in the newer version release ?

**Comment by SCadilhac** [comment]
Yes the commit will be included in next version. For now, you may comment out `cli.debug` line from the NX-OS driver JS file.
