### ISSUE TITLE
Netshot Not starting up after change of groups.

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#327]
Hi,

After changed some of the groups folders seems something broke :(

could it be because I still had the tasks scheduled? 

Starting Netshot version 0.20.0.
12:32:47.992 [main] INFO onl.netfishers.netshot.Netshot -- Starting Netshot
12:32:47.995 [main] WARN onl.netfishers.netshot.Netshot -- Unable to read the configuration file netshot.conf.
12:32:47.996 [main] WARN onl.netfishers.netshot.Netshot -- Configuration file /etc/netshot.conf successfully read.
12:32:48.003 [main] INFO onl.netfishers.netshot.Netshot -- Switching to file logging, into /var/log/netshot/netshot.log, level INFO, rotation using 5 files of max 2MB.
Database is up to date, no changesets to execute
NETSHOT FATAL ERROR: Cannot invoke "org.hibernate.persister.entity.EntityPersister.getRootEntityName()" because "this.persister" is null
java.lang.NullPointerException: Cannot invoke "org.hibernate.persister.entity.EntityPersister.getRootEntityName()" because "this.persister" is null
        at org.hibernate.engine.spi.EntityKey.generateHashCode(EntityKey.java:61)
        at org.hibernate.engine.spi.EntityKey.<init>(EntityKey.java:56)
        at org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl.resolveEntityKey(EntityInitializerImpl.java:709)
        at org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl.resolveKey(EntityInitializerImpl.java:579)
        at org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl.resolveKey(EntityInitializerImpl.java:452)
        at org.hibernate.sql.results.graph.entity.internal.EntityInitializerImpl.resolveKey(EntityInitializerImpl.java:96)
        at org.hibernate.sql.results.internal.StandardRowReader.coordinateInitializers(StandardRowReader.java:235)
        at org.hibernate.sql.results.internal.StandardRowReader.readRow(StandardRowReader.java:141)
        at org.hibernate.sql.results.spi.ListResultsConsumer.read(ListResultsConsumer.java:249)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:201)
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:35)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:224)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:102)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.executeQuery(JdbcSelectExecutor.java:91)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:165)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$1(ConcreteSqmSelectQueryPlan.java:152)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:442)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:362)
        at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:380)
        at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:136)
        at onl.netfishers.netshot.TaskManager.rescheduleAll(TaskManager.java:558)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:574)
netshot.service: Main process exited, code=exited, status=1/FAILURE
netshot.service: Failed with result 'exit-code'.
netshot.service: Consumed 21.853s CPU time.

**Comment by pizu** [comment]
is there a way to delete all the scheduled tasks?

**Comment by pizu** [comment]
using:
SELECT *
FROM task
WHERE schedule_type = 2
  AND status = 4;

am able to see all tasks, if i delete the tasks that are related to the groups i have changed does something else break?

**Comment by pizu** [comment]
sorted by deleting the tasks related.

**Comment by SCadilhac** [comment]
Should be fixed in 0.20.1, please reopen if not the case.
