### ISSUE TITLE
Netshot 12.1

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#36]
After update I see

Feb 25 11:09:22 netshotala.air-astana.net systemd[1]: Started Netshot.
Feb 25 11:09:22 netshotala.air-astana.net java[13808]: Starting Netshot version 0.12.1.
Feb 25 11:09:22 netshotala.air-astana.net java[13808]: 11:09:22.314 [main] INFO onl.netfishers.netshot.Netshot - Starting Netshot
Feb 25 11:09:22 netshotala.air-astana.net java[13808]: 11:09:22.316 [main] ERROR onl.netfishers.netshot.Netshot - Unable to read the configuration file netshot.conf.
Feb 25 11:09:22 netshotala.air-astana.net java[13808]: 11:09:22.322 [main] INFO onl.netfishers.netshot.Netshot - Switching to file logging, into /var/log/ne... max 2MB.
Feb 25 11:09:25 netshotala.air-astana.net java[13808]: NETSHOT FATAL ERROR: Unable to connect to the database, see logs for more details

**Comment by SCadilhac** [comment]
Can you paste the content of `/var/log/netshot/netshot.log`?

**Comment by myroma** [comment]
2019-02-25 12:17:32,943 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2019-02-25 12:17:36,289 WARN  [main] DatabaseChangeLog: liquibase.statement.core.CreateSequenceStatement is not supported on mysql, but createSequence will still execute
2019-02-25 12:17:36,295 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
liquibase.exception.ValidationFailedException: Validation Failed:
     4 change sets check sum
          migration/netshot0.xml::0.5.2_1::netshot (generated) was: 8:cd1a235f1a3856f1f7a7027c19e9734e but is now: 8:1534a0df4e73e7c5877f8f03c0ffde51
          migration/netshot0.xml::0.7.0_1::netshot (generated) was: 8:15f3d1c182d476014b22eceaa5ef9bfe but is now: 8:f0b61c2a17e0663fb534ae3899925147
          migration/netshot0.xml::0.7.3_1::netshot (generated) was: 8:88d950f3e27089a74d2c34d02734f41b but is now: 8:5c0cc8fccb8ad7358fa9e93797a820e7
          migration/netshot0.xml::0.8.0_1::netshot (generated) was: 8:fe5eec9841396420536e66703e423199 but is now: 8:ea75c0b02633a5bff0c6cb261ed1c9bf

	at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:276)
	at liquibase.Liquibase.update(Liquibase.java:198)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at onl.netfishers.netshot.Database.update(Database.java:273)
	at onl.netfishers.netshot.Netshot.main(Netshot.java:398)

**Comment by SCadilhac** [comment]
You may want to try to do the following:
* Stop Netshot
* Log into the DB: `mysql -u netshot -p netshot01`
* `DROP TABLE DATABASECHANGELOG;`
* `DROP TABLE DATABASECHANGELOGLOCK;`
* Start Netshot.

**Comment by myroma** [comment]
Thanks! It works!
