### ISSUE TITLE
Snapshot issue On Fortigate.

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#47]
Random Tasks that run everyday, are stuck..

![image](https://user-images.githubusercontent.com/7047326/56786416-2e21de80-67f9-11e9-8db1-e923026a0048.png)

**Comment by SCadilhac** [comment]
You have to provide more information in order to get some help identifying the issue.
Are you running the last version of Netshot and the last FortiGate driver?
If yes, a full CLI debug of the task would be useful to troubleshoot further:

- Add `netshot.log.class.onl.netfishers.netshot.device.access.Cli = ALL` to the Netshot configuration file on the server, e.g. `/etc/netshot.conf`
- Restart Netshot, e.g. `service netshot restart`
- Manually start the snapshot several times until the issue appears.
- Explore `/var/log/netshot/netshot.log` to find out what can be blocking out.
- Remove the line from `/etc/netshot.conf`and restart Netshot to stop debugging mode.

Note: If your Netshot instance contains a lot of devices, you should not keep this setting enabled while all the snapshots are running, as this results in very verbose logs.

**Comment by pizu** [comment]
I have 137 devices, what do you recommend? also it is hanging always on the same device.. after the restart it didn't hang once..

**Comment by pizu** [comment]
after the 10th snapshot I got 1 stuck in the task,, remaining running.. but no errors in the log file.

**Comment by SCadilhac** [comment]
Have you enabled the debug mode as suggested? If yes, can you provide the logs?

**Comment by SCadilhac** [comment]
22d5a639a6d422f4593459c37ebdfb2ebc61f49b should fix it I guess. It will be integrated in the next release, in the meantime you can install it manually (see https://github.com/netfishers-onl/Netshot/wiki/Loading-an-alternative-driver-into-Netshot).

**Comment by pizu** [comment]
Hi,

Yes I had enabled the diagnostics command and the  backup was being done full but the task was hanging for some reason, only on the fortigatem, even on the v0.12.7

**Comment by SCadilhac** [comment]
Have you tried with the last driver as mentioned? 0.12.7 was released before and thus does NOT integrate the fixed driver.

**Comment by pizu** [comment]
Error:

==> /var/log/netshot/audit.log <==
2019-06-17 09:30:00,644 AAA: HTTP Request https://netshot.corporate.intra:8443/api/refresheddevicetypes by user netadmin.

==> /var/log/netshot/netshot.log <==
2019-06-17 09:30:00,652 ERROR [grizzly-http-server-2] DeviceDriver: Error while loading user device driver /usr/local/netshot/drivers/Fortinet_FortiOS.js.
javax.script.ScriptException: <eval>:7:0 Expected an operand but found <
<!DOCTYPE html>
^ in <eval> at line number 7 at column number 0
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:537)
        at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:524)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
        at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
        at onl.netfishers.netshot.device.DeviceDriver.<init>(DeviceDriver.java:354)
        at onl.netfishers.netshot.device.DeviceDriver.refreshDrivers(DeviceDriver.java:222)
        at onl.netfishers.netshot.RestService.getDeviceTypesAndRefresh(RestService.java:1765)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:76)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:148)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:191)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:243)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:103)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:493)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:415)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:104)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:277)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:316)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:298)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:268)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:289)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:256)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:703)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:416)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:370)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:389)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:342)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:229)
        at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:147)
        at org.glassfish.grizzly.servlet.FilterChainImpl.invokeFilterChain(FilterChainImpl.java:106)
        at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:226)
        at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:173)
        at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
        at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
        at java.lang.Thread.run(Thread.java:748)
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:7:0 Expected an operand but found <
<!DOCTYPE html>
^
        at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
        at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
        at jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:3182)
        at jdk.nashorn.internal.parser.Parser.expression(Parser.java:3282)
        at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1150)
        at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
        at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
        at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
        at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
        at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
        at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
        at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
        at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
        at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
        ... 41 common frames omitted

**Comment by pizu** [comment]
Sorted. - when file was downloaded somehow it got corrupted. - will test v4.1 driver and get back.
