### ISSUE TITLE
upgrade issue from 0.7.1 to 0.13.1

### ISSUE THREAD

**Issue by privet971** [netfishers-onl/Netshot#53]
Hello,

I tried to upgrade straight from 0.7.1 to 0.13.1 but netshot don't start.

mysql version: Ver 14.14 Distrib 5.1.69
java version:1.8.0_221

From netshot.log:
2019-08-13 08:26:31,282 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2019-08-13 08:26:31,674 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
java.sql.SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:79)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at onl.netfishers.netshot.Database.update(Database.java:269)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:421)
Caused by: com.mysql.cj.exceptions.UnableToConnectException: CLIENT_PLUGIN_AUTH is required
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
        at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:205)
        at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1442)
        at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
        ... 7 common frames omitted

Maybe  I must upgrade my mysql version ?

**Comment by SCadilhac** [comment]
Hi @privet971, yes you probably need to upgrade MySQL.
Don't forget to properly backup your DB before anything.

**Comment by privet971** [comment]
ok, I’ll do it , thanks

**Comment by privet971** [comment]
Sorry for this very long post:

I tried to migrate on a new server ( last java 11.0.4+11, mariadb 10.3.15-MariaDB-1 Debian 10)
Then I loaded the last db backup an tried to start Netshot, but ......there is another issue:

logs show:
019-08-16 10:59:21,908 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2019-08-16 10:59:32,442 WARN  [main] DatabaseChangeLog: liquibase.statement.core.CreateSequenceStatement is not supported on mariadb, but createSequence will still execute
2019-08-16 10:59:53,658 ERROR [main] ChangeSet: Change Set migration/netshot0.xml::0.12.0_1::netshot (generated) failed.  Error: Can't create table `netshot01`.`diagnostic_result` (errno: 150 "Foreign key constraint is incorrectly formed") [Failed SQL: ALTER TABLE netshot01.diagnostic_result ADD CONSTRAINT FK_1fa1ox5d3abi5ridwnhovpmou FOREIGN KEY (device) REFERENCES netshot01.device (id) ON UPDATE NO ACTION ON DELETE NO ACTION]
2019-08-16 10:59:53,671 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
liquibase.exception.MigrationFailedException: Migration failed for change set migration/netshot0.xml::0.12.0_1::netshot (generated):
     Reason: liquibase.exception.DatabaseException: Can't create table `netshot01`.`diagnostic_result` (errno: 150 "Foreign key constraint is incorrectly formed") [Failed SQL: ALTER TABLE netshot01.diagnostic_result ADD CONSTRAINT FK_1fa1ox5d3abi5ridwnhovpmou FOREIGN KEY (device) REFERENCES netshot01.device (id) ON UPDATE NO ACTION ON DELETE NO ACTION]
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
        at liquibase.Liquibase.update(Liquibase.java:202)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at onl.netfishers.netshot.Database.update(Database.java:272)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:421)

Apparently, the migration from mysql to mariaDB don't seem ok 

If it's relevant:
-diagnostic_result table exist but it's empty 
-DATABASECHANGELOG contains 6 lines:
	('0.5.2_1', 'netshot (generated)', 'migration/netshot0.xml', '2019-08-16 10:59:32', 1, 'MARK_RAN', '8:cd1a235f1a3856f1f7a7027c19e9734e', 'createTable tableName=check_compliance_task; createTable tableName=check_group_compliance_task; createTable tableName=check_group_software_task; createTable tableName=check_result; createTable tableName=config; createTable tableName=config_attribu...', '', NULL, '3.6.2', NULL, NULL, '5967571560'),
	('0.7.0_1', 'netshot (generated)', 'migration/netshot0.xml', '2019-08-16 10:59:32', 2, 'MARK_RAN', '8:15f3d1c182d476014b22eceaa5ef9bfe', 'addColumn tableName=device_credential_set; addColumn tableName=device; addColumn tableName=device; addColumn tableName=device; addColumn tableName=device; addColumn tableName=device; addColumn tableName=device; addUniqueConstraint constraintName=U...', '', NULL, '3.6.2', NULL, NULL, '5967571560'),
	('0.7.2_1', 'netshot (generated)', 'migration/netshot0.xml', '2019-08-16 10:59:32', 3, 'MARK_RAN', '8:03bf64d7bda8b8d33394a43c35b50b5b', 'dropUniqueConstraint constraintName=UK_49k44bri62v926c9f4uw4t68q, tableName=device', '', NULL, '3.6.2', NULL, NULL, '5967571560'),
	('0.7.3_1', 'netshot (generated)', 'migration/netshot0.xml', '2019-08-16 10:59:32', 4, 'EXECUTED', '8:88d950f3e27089a74d2c34d02734f41b', 'addColumn tableName=software_rule; addColumn tableName=software_rule', '', NULL, '3.6.2', NULL, NULL, '5967571560'),
	('0.8.0_1', 'netshot (generated)', 'migration/netshot0.xml', '2019-08-16 10:59:51', 5, 'EXECUTED', '8:fe5eec9841396420536e66703e423199', 'createTable tableName=debug_log; addColumn tableName=task; addColumn tableName=task; createIndex indexName=FK_kbqvwwy2olpj1jbwxfqhvl97l, tableName=task; addForeignKeyConstraint baseTableName=task, constraintName=FK_kbqvwwy2olpj1jbwxfqhvl97l, refer...', '', NULL, '3.6.2', NULL, NULL, '5967571560'),
	('0.10.1_1', 'netshot (generated)', 'migration/netshot0.xml', '2019-08-16 10:59:51', 6, 'EXECUTED', '8:341a91820b4fe6e4e41b16b2b121bee9', 'modifyDataType columnName=private_key, tableName=device_credential_set; modifyDataType columnName=public_key, tableName=device_credential_set; addColumn tableName=device_credential_set; addColumn tableName=device_credential_set; addColumn tableNam...', '', NULL, '3.6.2', NULL, NULL, '5967571560');
/

**Comment by SCadilhac** [comment]
- You should use Java 8 only (Oracle or OpenJDK).
- I haven't made any testing with MariaDB 10.x, can you try with 5.x?

**Comment by SCadilhac** [comment]
The foreign key creation fails. You can try to run the SQL creation query in MySQL shell to get more details on the issue.
Otherwise, you can try:
1. Re-create an empty database
2. Start Netshot once to let it create the structure, and stop it
3. Import the data only from your backup, not the structure.
4. Start Netshot
