### ISSUE TITLE
Problem with checkpoint GAIA SG3100

### ISSUE THREAD

**Issue by hemh** [netfishers-onl/Netshot#59]
Hi Sylvain,

I try to backup a CP SG-3100 but I got this error:

[ERROR] Error while downloading file for attribute key backupArchive: /var/local/netshot/da860f30-f036-4dbd-aa0b-fc4230009a9b.data (No such file or directory)
[ERROR] Error while running snapshot using driver CheckpointGaia-v.hemh: 'java.io.FileNotFoundException: /var/local/netshot/da860f30-f036-4dbd-aa0b-fc4230009a9b.data (No such file or directory) in at line number 342 at column number 3'.
Download debug logs

Additionally, I had to modify the script by adding this line in the CLI portion to get rid of the lock.

var lockdatabaseoverride = cli.command("lock database override");

**Comment by SCadilhac** [comment]
Did you create `/var/local/netshot` folder with the correct permissions?
If so, can you share the full error from `/var/log/netshot/netshot.log`?

**Comment by hemh** [comment]
Hi Sylvain,

Yes the file /var/local/netshot was not created, now it is. Snapshot still failed.

Here is the log from the task status:
**_[INFO] Snapshot task for device [NONAME] (216.113.25.12).
[ERROR] Error while taking the snapshot: java.io.FileNotFoundException: /var/local/netshot/921e2a67-dfd3-4fea-a73e-43ba287d217a.data (Permission denied) in at line number 341 at column number 3
[INFO] Downloading '/var/log/CPbackup/backups/backup_calabfw01_28_Oct_2019_15_32.tgz' to '/var/local/netshot/921e2a67-dfd3-4fea-a73e-43ba287d217a.data' using SCP.
[DEBUG] File size: 771 bytes
[DEBUG] Name: ' Config lock is owned by admin. Use the command 'lock database override' to acquire the lock.'
[ERROR] Error while downloading file for attribute key backupArchive: /var/local/netshot/921e2a67-dfd3-4fea-a73e-43ba287d217a.data (Permission denied)
[ERROR] Error while running snapshot using driver CheckpointGaia: 'java.io.FileNotFoundException: /var/local/netshot/921e2a67-dfd3-4fea-a73e-43ba287d217a.data (Permission denied) in at line number 341 at column number 3'_**

And here is the log from /var/log/netshot/netshot.log:

**_2019-10-28 15:25:02,482 WARN  [QuartzScheduler_Worker-2] JsConfigHelper: Error during snapshot while downloading file for attribute key 'backupArchive'.
2019-10-28 15:25:02,513 ERROR [QuartzScheduler_Worker-2] SnapshotCliScript: Error while running snapshot using driver CheckpointGaia.
javax.script.ScriptException: java.io.FileNotFoundException: /var/local/netshot/c578eeac-bfb7-4a1f-85bd-2889c6c007cc.data (Permission denied) in <eval> at line number 341 at column number 3
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.script.SnapshotCliScript.run(SnapshotCliScript.java:92)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:240)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:194)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:200)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:90)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jdk.nashorn.internal.runtime.ECMAException: java.io.FileNotFoundException: /var/local/netshot/c578eeac-bfb7-4a1f-85bd-2889c6c007cc.data (Permission denied)
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$8417$4047AAAA$\^eval\_.snapshot(<eval>:341)
        at jdk.nashorn.internal.scripts.Script$Recompilation$8519$795AAAA$\^eval\_._connect(<eval>:534)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        ... 8 common frames omitted
Caused by: java.io.FileNotFoundException: /var/local/netshot/c578eeac-bfb7-4a1f-85bd-2889c6c007cc.data (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at onl.netfishers.netshot.device.access.Ssh.scpDownload(Ssh.java:343)
        at onl.netfishers.netshot.device.script.helper.JsConfigHelper.download(JsConfigHelper.java:184)
        at jdk.nashorn.internal.scripts.Script$Recompilation$8532$14036AAAA$\^eval\_._connect#download(<eval>:501)
        at jdk.nashorn.internal.scripts.Script$Recompilation$8417$4047AAAA$\^eval\_.snapshot(<eval>:334)
        ... 14 common frames omitted
2019-10-28 15:25:02,514 ERROR [QuartzScheduler_Worker-2] TakeSnapshotTask: Error while taking the snapshot.
javax.script.ScriptException: java.io.FileNotFoundException: /var/local/netshot/c578eeac-bfb7-4a1f-85bd-2889c6c007cc.data (Permission denied) in <eval> at line number 341 at column number 3
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.script.SnapshotCliScript.run(SnapshotCliScript.java:92)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:240)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:194)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:200)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:90)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jdk.nashorn.internal.runtime.ECMAException: java.io.FileNotFoundException: /var/local/netshot/c578eeac-bfb7-4a1f-85bd-2889c6c007cc.data (Permission denied)
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$8417$4047AAAA$\^eval\_.snapshot(<eval>:341)
        at jdk.nashorn.internal.scripts.Script$Recompilation$8519$795AAAA$\^eval\_._connect(<eval>:534)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        ... 8 common frames omitted
Caused by: java.io.FileNotFoundException: /var/local/netshot/c578eeac-bfb7-4a1f-85bd-2889c6c007cc.data (Permission denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at onl.netfishers.netshot.device.access.Ssh.scpDownload(Ssh.java:343)
        at onl.netfishers.netshot.device.script.helper.JsConfigHelper.download(JsConfigHelper.java:184)
        at jdk.nashorn.internal.scripts.Script$Recompilation$8532$14036AAAA$\^eval\_._connect#download(<eval>:501)
        at jdk.nashorn.internal.scripts.Script$Recompilation$8417$4047AAAA$\^eval\_.snapshot(<eval>:334)
        ... 14 common frames omitted
[root@cardlntsh1 netshot]#_**

**Comment by hemh** [comment]
Additionnal info, in the folder Netshot, I reveive a ".data" file with this line inside:

scp -f '/var/log/CPbackup/backups/backup_calabfw01_28_Oct_2019_15_35.tgz

**Comment by SCadilhac** [comment]
`permission denied`: has the `netshot` user x and w permissions on `/var/local/netshot`?
