### ISSUE TITLE
service do not start after yum update

### ISSUE THREAD

**Issue by myroma** [netfishers-onl/Netshot#60]
[root@netshotala ~]# systemctl status netshot
Б≈▐ netshot.service - Netshot
   Loaded: loaded (/etc/systemd/system/netshot.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2019-11-06 10:56:40 +06; 1s ago
  Process: 11405 ExecStart=/usr/bin/java -jar /usr/local/netshot/netshot.jar (code=exited, status=1/FAILURE)
 Main PID: 11405 (code=exited, status=1/FAILURE)

Nov 06 10:56:38 netshotala.air-astana.net systemd[1]: Started Netshot.
Nov 06 10:56:38 netshotala.air-astana.net java[11405]: Starting Netshot version 0.14.1.
Nov 06 10:56:38 netshotala.air-astana.net java[11405]: 10:56:38.328 [main] INFO onl.netfishers.netshot.Netshot - Starting Netshot
Nov 06 10:56:38 netshotala.air-astana.net java[11405]: 10:56:38.331 [main] ERROR onl.netfishers.netshot.Netshot - Unable to read the configuration file netshot.conf.
Nov 06 10:56:38 netshotala.air-astana.net java[11405]: 10:56:38.336 [main] INFO onl.netfishers.netshot.Netshot - Switching to file logging, into /var/log/ne... max 2MB.
Nov 06 10:56:40 netshotala.air-astana.net java[11405]: NETSHOT FATAL ERROR: Unable to connect to the database, see logs for more details
Nov 06 10:56:40 netshotala.air-astana.net systemd[1]: netshot.service: main process exited, code=exited, status=1/FAILURE

**Comment by myroma** [comment]
Here is log output:

2019-11-07 16:30:11,782 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2019-11-07 16:30:13,773 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:835)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:455)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at onl.netfishers.netshot.Database.update(Database.java:269)
	at onl.netfishers.netshot.Netshot.main(Netshot.java:421)
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:351)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.negotiateSSLConnection(NativeAuthenticationProvider.java:777)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:486)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1442)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:955)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
	... 7 common frames omitted
Caused by: javax.net.ssl.SSLException: java.security.ProviderException: Could not derive key
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.handleException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at com.mysql.cj.protocol.ExportControlled.performTlsHandshake(ExportControlled.java:315)
	at com.mysql.cj.protocol.StandardSocketFactory.performTlsHandshake(StandardSocketFactory.java:188)
	at com.mysql.cj.protocol.a.NativeSocketConnection.performTlsHandshake(NativeSocketConnection.java:99)
	at com.mysql.cj.protocol.a.NativeProtocol.negotiateSSLConnection(NativeProtocol.java:347)
	... 14 common frames omitted
Caused by: java.security.ProviderException: Could not derive key
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:133)
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:163)
	at javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:648)
	at sun.security.ssl.ECDHCrypt.getAgreedSecret(Unknown Source)
	at sun.security.ssl.ClientHandshaker.serverHelloDone(Unknown Source)
	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)
	at sun.security.ssl.Handshaker.processLoop(Unknown Source)
	at sun.security.ssl.Handshaker.process_record(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	... 20 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: null
	at sun.security.ec.ECDHKeyAgreement.deriveKey(Native Method)
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:130)
	... 29 common frames omitted

**Comment by SCadilhac** [comment]
Looks like the MySQL DB is down...?

**Comment by myroma** [comment]
> Looks like the MySQL DB is down...?

MySQL is up and working fine

**Comment by myroma** [comment]
mysqld.service - MySQL Server
   Loaded: loaded (/usr/lib/systemd/system/mysqld.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2019-11-06 11:56:53 +06; 1 day 19h ago
     Docs: man:mysqld(8)
           http://dev.mysql.com/doc/refman/en/using-systemd.html
 Main PID: 1856 (mysqld)
   CGroup: /system.slice/mysqld.service
           Б■■Б■─1856 /usr/sbin/mysqld --daemonize --pid-file=/var/run/mysqld/mysqld.pid

Nov 06 11:56:53 netshotala.air-astana.net systemd[1]: Starting MySQL Server...
Nov 06 11:56:53 netshotala.air-astana.net systemd[1]: Started MySQL Server.
[root@netshotala ~]# mysql -u netshot -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 101
Server version: 5.7.28 MySQL Community Server (GPL)

Copyright (c) 2000, 2019, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> USE netshot01
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql>

**Comment by SCadilhac** [comment]
Indeed. Which Java version are you using? It should be the last Java 8 release.

**Comment by myroma** [comment]
[root@netshotala ~]# java -version 2>&1 | grep version
java version "1.8.0_201"

**Comment by SCadilhac** [comment]
I've been through the logs, the connection is failing on SSL negotiation with MySQL. You can try to disable SSL (for now) by changing the connection URL in `/etc/netshot.conf`:

`netshot.db.url = jdbc:mysql://localhost/netshot01?serverTimezone=UTC&useSSL=false`

**Comment by myroma** [comment]
Thanks. App is started with no ssl!
But why did it happen? Is there support ssl connection to mysql in app?

**Comment by SCadilhac** [comment]
For SSL to work, the client (here Netshot) has to trust the certificate of MySQL server. Thus there are additional steps, it can't work out-of-the-box.
