### ISSUE TITLE
Unable to read the configuration.

### ISSUE THREAD

**Issue by PatrickDenis** [netfishers-onl/Netshot#64]
Hi, 

Im having some problem installing Netshot.

I have the same behavior on ubuntu 18.04 and 16.04 and im using java8. ( install info from here https://tecadmin.net/install-oracle-java-8-ubuntu-via-ppa/ )
This is done in a VM 

I saw the same error in the issues/fix in 2018 and follow the recommendation and redownload / reinstall everything and still the same problem.

i must be missing something out 

These are my 2 problems : 

1- I dont see the netshot.jks files after creating the SSL
2- When i start the service i see this error when i check the status : 

### > oot@ubuntu:/home/patrickdenis/tmp# service netshot status
> â— netshot.service - Netshot
>    Loaded: loaded (/etc/systemd/system/netshot.service; enabled; vendor preset: enabled)
>    Active: active (running) since Tue 2020-03-24 16:30:43 PDT; 1s ago
>  Main PID: 16672 (java)
>    CGroup: /system.slice/netshot.service
>            â””â”€16672 /usr/bin/java -jar /usr/local/netshot/netshot.jar
> 
> Mar 24 16:30:43 ubuntu systemd[1]: Started Netshot.
> Mar 24 16:30:43 ubuntu java[16672]: Starting Netshot version 0.14.1.
> Mar 24 16:30:43 ubuntu java[16672]: 16:30:43.732 [main] INFO onl.netfishers.netshot.Netshot - Starting Netshot
> Mar 24 16:30:43 ubuntu java[16672]: 16:30:43.734 [main] E**RROR onl.netfishers.netshot.Netshot - Unable to read the configu**
> Mar 24 16:30:43 ubuntu java[16672]: 16:30:43.742 [main] INFO onl.netfishers.netshot.Netshot - Switching to file logging, 
> lines 1-12/12 (END)
> [2]+  Stopped                 service netshot status

Thanks in advance for any info that could help. 

Merci à l'avance ;)

**Comment by PatrickDenis** [comment]
update : 

Again reinstalled everything : 

and this is the same behavior : 

root@netshot:/home/patrickdenis# service netshot status
â— netshot.service - Netshot
   Loaded: loaded (/etc/systemd/system/netshot.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2020-03-25 00:49:05 UTC; 36s ago
  Process: 9465 ExecStart=/usr/bin/java -jar /usr/local/netshot/netshot.jar (code=exited, status=1/FAILURE)
 Main PID: 9465 (code=exited, status=1/FAILURE)

Mar 25 00:48:47 netshot systemd[1]: Started Netshot.
Mar 25 00:48:47 netshot java[9465]: Starting Netshot version 0.14.1.
Mar 25 00:48:47 netshot java[9465]: 00:48:47.255 [main] INFO onl.netfishers.netshot.Netshot - Starting Netshot
Mar 25 00:48:47 netshot java[9465]: 00:48:47.258 [main] ERROR onl.netfishers.netshot.Netshot - Unable to read the configu
Mar 25 00:48:47 netshot java[9465]: 00:48:47.266 [main] INFO onl.netfishers.netshot.Netshot - Switching to file logging, 
Mar 25 00:49:05 netshot java[9465]: NETSHOT FATAL ERROR
Mar 25 00:49:05 netshot java[9465]: java.lang.RuntimeException: Error with the REST service, see logs for more details.
Mar 25 00:49:05 netshot java[9465]:         at onl.netfishers.netshot.RestService.run(RestService.java:369)
Mar 25 00:49:05 netshot systemd[1]: netshot.service: Main process exited, code=exited, status=1/FAILURE
Mar 25 00:49:05 netshot systemd[1]: netshot.service: Failed with result 'exit-code'.
 ^X

**Comment by PatrickDenis** [comment]
and more detail 

2020-03-25 01:18:23,526 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
org.postgresql.util.PSQLException: SSL error: Remote host closed connection during handshake
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:42)
        at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:435)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:94)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
        at org.postgresql.Driver.makeConnection(Driver.java:454)
        at org.postgresql.Driver.connect(Driver.java:256)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at onl.netfishers.netshot.Database.update(Database.java:269)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:421)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
        at org.postgresql.ssl.MakeSSL.convert(MakeSSL.java:40)
        ... 11 common frames omitted
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(InputRecord.java:505)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
        ... 15 common frames omitted
2020-03-25 01:19:22,063 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2020-03-25 01:19:28,128 WARN  [main] DatabaseChangeLog: liquibase.statement.core.CreateSequenceStatement is not supported on mysql, but createSequence will still execute
2020-03-25 01:19:58,856 WARN  [main] Netshot: Netshot is started
2020-03-25 01:20:24,309 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
