### ISSUE TITLE
v0.13.0 to v0.13.1 Errors

### ISSUE THREAD

**Issue by pizu** [netfishers-onl/Netshot#69]
020-06-10 16:36:13,254 INFO  [main] StdSchedulerFactory: Quartz scheduler 'QuartzScheduler' initialized from an externally provided properties instance.
2020-06-10 16:36:13,254 INFO  [main] StdSchedulerFactory: Quartz scheduler version: 2.2.3
2020-06-10 16:36:13,255 INFO  [main] QuartzScheduler: Scheduler QuartzScheduler_$_NON_CLUSTERED started.
2020-06-10 16:36:13,263 INFO  [main] Netshot: Updating the database schema, if necessary.
2020-06-10 16:36:16,635 INFO  [main] JdbcExecutor: SELECT COUNT(*) FROM netshot01.DATABASECHANGELOGLOCK
2020-06-10 16:36:16,640 INFO  [main] JdbcExecutor: SELECT COUNT(*) FROM netshot01.DATABASECHANGELOGLOCK
2020-06-10 16:36:16,646 INFO  [main] JdbcExecutor: SELECT `LOCKED` FROM netshot01.DATABASECHANGELOGLOCK WHERE ID=1
2020-06-10 16:36:16,704 INFO  [main] StandardLockService: Successfully acquired change log lock
2020-06-10 16:36:18,490 INFO  [main] JdbcExecutor: SELECT MD5SUM FROM netshot01.DATABASECHANGELOG WHERE MD5SUM IS NOT NULL LIMIT 1
2020-06-10 16:36:18,494 INFO  [main] JdbcExecutor: SELECT COUNT(*) FROM netshot01.DATABASECHANGELOG
2020-06-10 16:36:18,496 INFO  [main] StandardChangeLogHistoryService: Reading from netshot01.DATABASECHANGELOG
2020-06-10 16:36:18,497 INFO  [main] JdbcExecutor: SELECT * FROM netshot01.DATABASECHANGELOG ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
2020-06-10 16:36:18,691 INFO  [main] StandardLockService: Successfully released change log lock
2020-06-10 16:36:18,694 INFO  [main] Netshot: Initializing access to the database.
2020-06-10 16:36:18,804 INFO  [main] Version: HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
2020-06-10 16:36:18,808 INFO  [main] Version: HHH000412: Hibernate Core {4.3.11.Final}
2020-06-10 16:36:18,810 INFO  [main] Environment: HHH000206: hibernate.properties not found
2020-06-10 16:36:18,811 INFO  [main] Environment: HHH000021: Bytecode provider name : javassist
2020-06-10 16:36:20,745 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.RunDeviceGroupScriptTask
2020-06-10 16:36:20,746 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.CheckGroupComplianceTask
2020-06-10 16:36:20,746 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.RunDeviceScriptTask
2020-06-10 16:36:20,746 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.ScanSubnetsTask
2020-06-10 16:36:20,746 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.TakeGroupSnapshotTask
2020-06-10 16:36:20,746 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.Traceroute4Task
2020-06-10 16:36:20,746 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.DiscoverDeviceTypeTask
2020-06-10 16:36:20,746 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.CheckGroupSoftwareTask
2020-06-10 16:36:20,746 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.RunDiagnosticsTask
2020-06-10 16:36:20,747 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.GenerateReportTask
2020-06-10 16:36:20,747 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.RunGroupDiagnosticsTask
2020-06-10 16:36:20,747 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.TakeSnapshotTask
2020-06-10 16:36:20,747 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.PurgeDatabaseTask
2020-06-10 16:36:20,747 INFO  [main] Database: Registering task class onl.netfishers.netshot.work.tasks.CheckComplianceTask
2020-06-10 16:36:20,823 INFO  [main] C3P0ConnectionProvider: HHH010002: C3P0 using driver: com.mysql.jdbc.Driver at URL: jdbc:mysql://localhost/netshot01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Malta
2020-06-10 16:36:20,824 INFO  [main] C3P0ConnectionProvider: HHH000046: Connection properties: {user=netshot, password=****}
2020-06-10 16:36:20,824 INFO  [main] C3P0ConnectionProvider: HHH000006: Autocommit mode: false
2020-06-10 16:36:20,834 INFO  [main] MLog: MLog clients using log4j logging.
2020-06-10 16:36:20,958 INFO  [main] C3P0Registry: Initializing c3p0-0.9.1.1 [built 15-March-2007 01:32:31; debug? true; trace: 10]
2020-06-10 16:36:21,031 INFO  [main] AbstractPoolBackedDataSource: Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@d0250568 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@7567e55f [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, debugUnreturnedConnectionStackTraces -> true, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 2ukv9iaa180tcs0e5wcrs|591fd34d, idleConnectionTestPeriod -> 0, initialPoolSize -> 5, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 1800, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 30, maxStatements -> 50, maxStatementsPerConnection -> 0, minPoolSize -> 5, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@ab19d076 [ description -> null, driverClass -> null, factoryClassLocation -> null, identityToken -> 2ukv9iaa180tcs0e5wcrs|4564e94b, jdbcUrl -> jdbc:mysql://localhost/netshot01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Malta, properties -> {user=******, password=******} ], preferredTestQuery -> null, propertyCycle -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 1800, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, factoryClassLocation -> null, identityToken -> 2ukv9iaa180tcs0e5wcrs|bcb09a6, numHelperThreads -> 3 ]
2020-06-10 16:36:21,150 INFO  [main] Dialect: HHH000400: Using dialect: org.hibernate.dialect.MySQL5Dialect
2020-06-10 16:36:21,165 INFO  [main] LobCreatorBuilder: HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
2020-06-10 16:36:21,732 INFO  [main] TransactionFactoryInitiator: HHH000399: Using default transaction strategy (direct JDBC transactions)
2020-06-10 16:36:21,738 INFO  [main] ASTQueryTranslatorFactory: HHH000397: Using ASTQueryTranslatorFactory
2020-06-10 16:36:22,145 INFO  [main] JavaScriptRule: Reading the JavaScript rule loader code from the resource JS file.
2020-06-10 16:36:22,889 INFO  [main] Netshot: Loading the device drivers
2020-06-10 16:36:22,894 INFO  [main] DeviceDriver: Reading the JavaScript driver loader code from the resource JS file.
2020-06-10 16:36:22,897 INFO  [main] DeviceDriver: Found user device driver file /usr/local/netshot/drivers/Fortinet_FortiOS.js.
2020-06-10 16:36:23,789 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=FortinetFortiOS, author=NetFishers, description=Fortinet FortiOS, version=4.1-debug].
2020-06-10 16:36:23,832 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,034 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=AlcatelLucentTiMOS, author=NetFishers, description=Alcatel-Lucent TiMOS, version=1.3].
2020-06-10 16:36:24,034 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,152 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CiscoStarOS, author=NetFishers, description=Cisco StarOS, version=1.3].
2020-06-10 16:36:24,153 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,326 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=AvayaERS, author=NetFishers, description=Avaya ERS, version=0.4.4].
2020-06-10 16:36:24,327 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,462 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CiscoIOS12, author=NetFishers, description=Cisco IOS and IOS-XE, version=1.6.2].
2020-06-10 16:36:24,463 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,529 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=BrocadeFastIron, author=NetFishers, description=Brocade FastIron, version=1.3].
2020-06-10 16:36:24,529 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,652 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=JuniperJunos, author=NetFishers, description=Juniper Junos, version=2.12].
2020-06-10 16:36:24,652 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,783 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CiscoIOSXR, author=NetFishers, description=Cisco IOS-XR, version=1.5].
2020-06-10 16:36:24,784 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,892 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CheckpointGaia, author=NetFishers, description=Checkpoint Gaia, version=2.0].
2020-06-10 16:36:24,892 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:24,974 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=Riverbed, author=Adrien GANDARIAS, description=RiOS, version=0.3].
2020-06-10 16:36:24,975 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,086 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CheckpointSPLAT, author=NetFishers, description=Checkpoint SPLAT, version=1.1].
2020-06-10 16:36:25,087 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,208 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=AristaEOS, author=NetFishers, description=Arista EOS, version=1.0.1].
2020-06-10 16:36:25,208 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,304 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CiscoNXOS, author=NetFishers, description=Cisco NX-OS 5+, version=1.8.1].
2020-06-10 16:36:25,304 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,390 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CiscoASA, author=NetFishers, description=Cisco ASA, version=1.4].
2020-06-10 16:36:25,390 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,433 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=SmartEdgeOS, author=NetFishers, description=Redback Networks SmartEdge OS, version=1.2].
2020-06-10 16:36:25,434 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,490 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=F5TMOS, author=NetFishers, description=F5 TM-OS, 11.x and newer, version=1.0].
2020-06-10 16:36:25,490 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,594 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CitrixNetscaler, author=NetFishers, description=Citrix NetScaler, version=1.1].
2020-06-10 16:36:25,595 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,667 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=CiscoACE, author=NetFishers, description=Cisco ACE, version=1.5.1].
2020-06-10 16:36:25,668 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,732 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=Palo Alto PAN-OS, author=Adrien GANDARIAS, description=PAN-OS, version=0.3].
2020-06-10 16:36:25,732 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,787 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=FortinetFortiOS, author=NetFishers, description=Fortinet FortiOS, version=4.1].
2020-06-10 16:36:25,787 WARN  [main] DeviceDriver: Skipping Netshot device driver file /usr/local/netshot/netshot.jar, because a similar driver is already loaded.
2020-06-10 16:36:25,788 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,839 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=HuaweiNE, author=NetFishers, description=Huawei NE Router, version=1.1].
2020-06-10 16:36:25,839 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,875 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=GigamonGigaVUE, author=NetFishers, description=Gigamon GigaVUE, version=1.1].
2020-06-10 16:36:25,875 INFO  [main] DeviceDriver: Found Netshot device driver file /usr/local/netshot/netshot.jar (in jar).
2020-06-10 16:36:25,911 INFO  [main] DeviceDriver: Loaded driver DeviceDriver [name=JuniperScreenOS, author=NetFishers, description=Juniper ScreenOS, version=1.1].
2020-06-10 16:36:25,912 INFO  [main] Netshot: Starting the Syslog server.
2020-06-10 16:36:25,912 INFO  [main] Netshot: Starting the SNMP v1/v2c trap receiver
2020-06-10 16:36:25,934 INFO  [main] Netshot: Starting the REST service
2020-06-10 16:36:25,956 INFO  [main] Netshot: Scheduling the existing tasks.
2020-06-10 16:36:25,956 INFO  [REST Service] RestService: Starting the Web/REST service thread.
2020-06-10 16:36:26,212 ERROR [REST Service] RestService: Fatal error with the REST service.
org.glassfish.grizzly.ssl.SSLContextConfigurator$GenericStoreException: java.io.IOException: keystore password was incorrect
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.createSSLContext(SSLContextConfigurator.java:535)
        at onl.netfishers.netshot.RestService.run(RestService.java:337)
Caused by: java.io.IOException: keystore password was incorrect
        at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2059)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:238)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.loadBytes(SSLContextConfigurator.java:668)
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.createSSLContext(SSLContextConfigurator.java:500)
        ... 1 common frames omitted
Caused by: java.security.UnrecoverableKeyException: failed to decrypt safe contents entry: javax.crypto.BadPaddingException: pad block corrupted
        ... 7 common frames omitted

**Comment by pizu** [comment]
Hi,

I just tried, i don't have any errors but it just stops from booting.


==> /var/log/netshot/netshot.log <==
2020-06-12 14:42:12,191 WARN  [main] Netshot: Logging to syslog datalog02.corporate.intra:514 has started
2020-06-12 14:42:12,195 INFO  [main] Netshot: Enabling BouncyCastle security.
2020-06-12 14:42:12,432 INFO  [main] Netshot: Initializing the task manager.
2020-06-12 14:42:12,488 INFO  [main] StdSchedulerFactory: Using default implementation for ThreadExecutor
2020-06-12 14:42:12,531 INFO  [main] SchedulerSignalerImpl: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2020-06-12 14:42:12,532 INFO  [main] QuartzScheduler: Quartz Scheduler v.2.2.3 created.
2020-06-12 14:42:12,534 INFO  [main] RAMJobStore: RAMJobStore initialized.
2020-06-12 14:42:12,536 INFO  [main] QuartzScheduler: Scheduler meta-data: Quartz Scheduler (v2.2.3) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2020-06-12 14:42:12,536 INFO  [main] StdSchedulerFactory: Quartz scheduler 'QuartzScheduler' initialized from an externally provided properties instance.
2020-06-12 14:42:12,536 INFO  [main] StdSchedulerFactory: Quartz scheduler version: 2.2.3
2020-06-12 14:42:12,537 INFO  [main] QuartzScheduler: Scheduler QuartzScheduler_$_NON_CLUSTERED started.
2020-06-12 14:42:12,537 INFO  [main] Netshot: Updating the database schema, if necessary.

**Comment by pizu** [comment]
after changing the level of log from info to debug am having incorrect password, if i go back to the 0.13.0 and using the same .jks file am not having any issues.

**Comment by pizu** [comment]
Hi,

do you have any suggestion please?

**Comment by SCadilhac** [comment]
What are the last logs? If you're still getting an error about incorrect keystore password, then check that the password you gave to the keystore does match the one passed via `netshot.http.ssl.keystore.pass` in `netshot.conf`.

**Comment by pizu** [comment]
Yes but if i use the newly created jks file on the v0.13.0 works but on the
v0.13.1 doesn't.. password is correct for sure I will re try again and
attach all logs in debug mode next week

Thanks for your reply.

**Comment by pizu** [comment]
Attached.
[netshot.log](https://github.com/netfishers-onl/Netshot/files/4814102/netshot.log)

**Comment by SCadilhac** [comment]
You didn't provide the precise Java version, the ouputs when generating the keystore, etc.

**Comment by pizu** [comment]
[image: image.png]

[image: image.png]

Regards,

Pizu

**Comment by pizu** [comment]
netshot.http.ssl.keystore.file = /usr/local/netshot/netshot.jks
netshot.http.ssl.keystore.pass = mypass

Regards,

Pizu

**Comment by SCadilhac** [comment]
> [image: image.png] [image: image.png] Regards, Pizu

Did you try to paste images? They are not visible here.

**Comment by pizu** [comment]
![image](https://user-images.githubusercontent.com/7047326/85417234-b885df80-b56f-11ea-914d-33966311c1f2.png)

![image](https://user-images.githubusercontent.com/7047326/85417252-bd4a9380-b56f-11ea-8e71-2787eba34873.png)

**Comment by SCadilhac** [comment]
The PKCS#12 keystore you are generating with this command is supported by Netshot 0.14.1 at minimum, as indicated in the notes. Either generate an old fashioned keystore (e.g. `keytool -genkey -keyalg RSA -alias selfsigned -keystore netshot.jks -storepass password -validity 3600 -keysize 2048`) or upgrade to a more recent version.

**Comment by pizu** [comment]
Hi,

Thanks yes that help and managed to upgrade to 0.13.1 and to 0.14.0
however then i tried to upgrade to 0.14.1 using the pkcs#12 and using the
.pfx and got same same error, did a server restart and worked, something
wrong with my server I believe - thanks for your help.

Regards,

Pizu
