### ISSUE TITLE
ASA Backup Issue

### ISSUE THREAD

**Issue by sajaltiwari** [netfishers-onl/Netshot#7]
Hello,
I am trying to backup config of ASA 9.5 and its not working for a context and physical both and getting below error
```

[05] Snapshot task for device [NONAME] (Device IP).
[03] Error while taking the snapshot: Error while running CLI macro 'enable' in 
[03] Device logs (1 next lines):
[1] Error while running function snapshot using driver CiscoASA: 'Error while running CLI macro 'enable' in at line number 118 at column number 4'.
```

Can you help me with this?

**Comment by SCadilhac** [comment]
Hello,

The ASA driver apparently can't get to the enable prompt.
Can you post the full output of the device when you log into it manually?

Sylvain

**Comment by sajaltiwari** [comment]
Hello,
There are two type of login for us, one in which the user can directly login to the enable mode and second from normal account to enable account. 

```
login as: abc
abc@test's password:
Type help or '?' for a list of available commands.
test# en
          ^
ERROR: % Invalid input detected at '^' marker.
```

**Comment by sajaltiwari** [comment]
Hello,
Any luck with the investigation for ASA  backup issue.

**Comment by SCadilhac** [comment]
Hello,

I just checked with an ASAv without enable password and it seems to work fine.
To troubleshoot further your issue, you would need to temporary enable additional debug logs.

On the server, edit the Netshot configuration file, e.g. `/etc/netshot.conf`, and add the following line:
`netshot.log.class.onl.netfishers.netshot.device.access.Cli = ALL`

Then restart Netshot:
`#service netshot restart`

Run the snapshot again and capture the output of `/var/log/netshot/netshot.log`.

Once done, rollback the change on the configuration file, as you don't want to run in full debugging mode the rest of the time.

Sylvain

**Comment by sajaltiwari** [comment]
Please find the error from the log.

`2018-01-12 01:53:37,304 ERROR [QuartzScheduler_Worker-1] DeviceDriver: Error while running function snapshot using driver CiscoASA.
javax.script.ScriptException: Error while running CLI macro 'enable' in <eval> at line number 118 at column number 4
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.DeviceDriver.cliRunFunction(DeviceDriver.java:1111)
        at onl.netfishers.netshot.device.DeviceDriver.takeSnapshot(DeviceDriver.java:1176)
        at onl.netfishers.netshot.device.DeviceDriver.runScript(DeviceDriver.java:1141)
        at onl.netfishers.netshot.device.Device.execute(Device.java:1204)
        at onl.netfishers.netshot.device.Device.takeSnapshot(Device.java:1175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:196)
        at onl.netfishers.netshot.device.Device_$$_jvstc27_6.takeSnapshot(Device_$$_jvstc27_6.java)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:190)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:88)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jdk.nashorn.internal.runtime.ECMAException: Error while running CLI macro 'enable'
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$115$2371A$\^eval\_._connect#_macro(<eval>:118)
        at jdk.nashorn.internal.scripts.Script$Recompilation$114$2016A$\^eval\_._connect#macro(<eval>:64)
        at jdk.nashorn.internal.scripts.Script$Recompilation$40$3849AAA$\^eval\_.snapshot(<eval>:192)
        at jdk.nashorn.internal.scripts.Script$Recompilation$113$800AAAAA$\^eval\_._connect(<eval>:375)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:647)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        ... 16 common frames omitted
2018-01-12 01:53:37,323 ERROR [QuartzScheduler_Worker-1] TakeSnapshotTask: Error while taking the snapshot.
javax.script.ScriptException: Error while running CLI macro 'enable' in <eval> at line number 118 at column number 4
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.DeviceDriver.cliRunFunction(DeviceDriver.java:1111)
        at onl.netfishers.netshot.device.DeviceDriver.takeSnapshot(DeviceDriver.java:1176)
        at onl.netfishers.netshot.device.DeviceDriver.runScript(DeviceDriver.java:1141)
        at onl.netfishers.netshot.device.Device.execute(Device.java:1204)
        at onl.netfishers.netshot.device.Device.takeSnapshot(Device.java:1175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.invoke(JavassistLazyInitializer.java:196)
        at onl.netfishers.netshot.device.Device_$$_jvstc27_6.takeSnapshot(Device_$$_jvstc27_6.java)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:190)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:88)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jdk.nashorn.internal.runtime.ECMAException: Error while running CLI macro 'enable'
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$115$2371A$\^eval\_._connect#_macro(<eval>:118)
        at jdk.nashorn.internal.scripts.Script$Recompilation$114$2016A$\^eval\_._connect#macro(<eval>:64)
        at jdk.nashorn.internal.scripts.Script$Recompilation$40$3849AAA$\^eval\_.snapshot(<eval>:192)
        at jdk.nashorn.internal.scripts.Script$Recompilation$113$800AAAAA$\^eval\_._connect(<eval>:375)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:647)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        ... 16 common frames omitted
`

**Comment by SCadilhac** [comment]
Hello,

This is probably due to the hyphens in the name of the context (`fw-automation-test`).
You can try the fix I just committed:

```
$ cd /usr/local/netshot/drivers
$ wget https://raw.githubusercontent.com/netfishers-onl/Netshot/master/src/main/resources/drivers/Cisco_ASA.js
```

And click _Reload the drivers_ on the Admin page.

**Comment by sajaltiwari** [comment]
Hello,
It logged into the device but while copying the config it failed.

`2018-01-12 08:21:59,377 DEBUG [QuartzScheduler_Worker-2] Cli: Command to send: ''.
2018-01-12 08:21:59,380 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'Type help or '?' for a list of available commands.
#######/fw-automation-test# '.
'.18-01-12 08:21:59,595 DEBUG [QuartzScheduler_Worker-2] Cli: Command to send: 'terminal pager 0
2018-01-12 08:21:59,829 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'terminal pager 0
'.
#######/fw-automation-test# '.zScheduler_Worker-2] Cli: Received data '
'.18-01-12 08:21:59,838 DEBUG [QuartzScheduler_Worker-2] Cli: Command to send: 'show version
2018-01-12 08:22:00,060 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 's'.
2018-01-12 08:22:00,064 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'ho'.
2018-01-12 08:22:00,073 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'w version

Cisco Adaptive Security Appliance Software Version 9.5(2) <context>
Device Manager Version 7.5(1)

Compiled on Sat 28-Nov-15 00:19 PST by builders

####### up 303 days 2 hours
failover cluster up 1 year 345 days

Hardware:   ASA5585-SSP-40

'.
2018-01-12 08:22:00,288 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'Licensed features for this user context:
Failover                          : Active/Active  perpetual
'.
2018-01-12 08:22:00,298 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'Encryption-DES                    : Enabled        perpetual
Encryption-3DES-AES               : Enabled        perpetual
Carrier                           : Disabled       perpetual
AnyConnect Premium Peers          : 0              perpetual
Other VPN Peers                   : 5              perpetual
AnyConnect for Mobile             : Disabled       perpetual
AnyConnect for Cisco VPN Phone    : Disabled       perpetual
Advanced Endpoint Assessment      : Disabled       perpetual
Botnet Traffic Filter             : Disabled       perpetual
10GE I/O                          : Enabled        perpetual
Cluster                           : Disabled       perpetual


Failover cluster licensed features for this user context:
Failover                          : Active/Active  perpetual
Encryption-DES                    : Enabled        perpetual
Encryption-3DES-AES               : Enabled        perpetual
Carrier                           : Disabled       perpetual
AnyConnect Premium Peers          : 0              perpetual
Other VPN Peers                   : 5              perpetual
AnyConnect for Mobile             : Disabled       perpetual
AnyConnect for Cisco VPN Phone    : Disabled       perpetual
'.
2018-01-12 08:22:00,516 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'Advanced Endpoint Assessment      : Disabled       perpetual
Botnet Traffic Filter             : Disabled       perpetual
'.
2018-01-12 08:22:00,520 DEBUG [QuartzScheduler_Worker-2] Cli: Received data '10GE I/O                          : Enabled        perpetual
'.
2018-01-12 08:22:00,523 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'Cluster                           : Disabled       perpetual
'.
2018-01-12 08:22:00,525 DEBUG [QuartzScheduler_Worker-2] Cli: Received data '

Image type          : Release
Key version         : A

Configuration last modified by user1 at 07:35:44.209 UTC Wed Jan 10 2018
#######/fw-automation-test# '.
'.18-01-12 08:22:00,624 DEBUG [QuartzScheduler_Worker-2] Cli: Command to send: 'show inventory
2018-01-12 08:22:00,844 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 's'.
2018-01-12 08:22:00,845 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'h'.
2018-01-12 08:22:00,847 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'o'.
2018-01-12 08:22:00,851 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'w'.
2018-01-12 08:22:00,852 DEBUG [QuartzScheduler_Worker-2] Cli: Received data ' '.
2018-01-12 08:22:00,854 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'i'.
2018-01-12 08:22:00,858 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'n'.
2018-01-12 08:22:00,863 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'ven'.
2018-01-12 08:22:00,869 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'tory
Name: "module 0", DESCR: "ASA 5585-X Security Services Processor-40 w 6GE,4 SFP+"
PID: ASA5585-SSP-40    , VID: V08     , SN: ?????????????????

Name: "Chassis", DESCR: "ASA 5585-X"
'.
2018-01-12 08:22:00,872 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'PID: ASA5585           , VID: V05     , SN: JMX19258068

Name: "TenGigabitEthernet0/6", DESCR: "10G Based-SR"
PID: SFP-10G-SR        , VID: V03 , SN: ????????????

'.
2018-01-12 08:22:01,069 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'Name: "TenGigabitEthernet0/7", DESCR: "10G Based-SR"
'.
2018-01-12 08:22:01,071 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'PID: SFP-10G-SR        , VID: V03 , SN: ?????????????????
'.
2018-01-12 08:22:01,073 DEBUG [QuartzScheduler_Worker-2] Cli: Received data '
Name: "TenGigabitEthernet0/8", DESCR: "10G Based-SR"
PID: SFP-10G-SR        , VID: V03 , SN: ???????????????

'.
2018-01-12 08:22:01,080 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'Name: "TenGigabitEthernet0/9", DESCR: "10G Based-SR"
PID: SFP-10G-SR        , VID: V03 , SN: ??????????
'.
2018-01-12 08:22:01,081 DEBUG [QuartzScheduler_Worker-2] Cli: Received data '
'.
2018-01-12 08:22:01,086 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'Driver Error, invalid query ready
Driver Error, invalid query ready
#######/fw-automation-test# '.
'.18-01-12 08:22:01,088 DEBUG [QuartzScheduler_Worker-2] Cli: Command to send: 'more system:running-config
2018-01-12 08:22:01,310 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'mo'.
2018-01-12 08:22:01,318 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 're system:ru'.
2018-01-12 08:22:01,323 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'nning-conf'.
2018-01-12 08:22:01,535 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'i'.
2018-01-12 08:22:01,539 DEBUG [QuartzScheduler_Worker-2] Cli: Received data 'g
                                  ^
ERROR: % Invalid input detected at '^' marker.
#######/fw-automation-test# '.
2018-01-12 08:22:01,725 WARN  [QuartzScheduler_Worker-2] SqlExceptionHelper: SQL Error: 1406, SQLState: 22001
2018-01-12 08:22:01,725 ERROR [QuartzScheduler_Worker-2] SqlExceptionHelper: Data truncation: Data too long for column 'family' at row 1
2018-01-12 08:22:01,755 ERROR [QuartzScheduler_Worker-2] TakeSnapshotTask: Error while taking the snapshot.
org.hibernate.exception.DataException: could not execute statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:69)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3285)
        at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3183)
        at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3525)
        at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:159)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
        at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1258)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425)
        at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101)
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:194)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:88)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'family' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3964)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
        ... 16 common frames omitted`

**Comment by SCadilhac** [comment]
OK, so `more system:running-config` doesn't seem to work on your device, either due to the version or to something specific...
