### ISSUE TITLE
JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by uchihaitachi2** [netfishers-onl/Netshot#73]
Hi,

I have an issue when I start Netshot for the first time.

Bellow error message:

**org.glassfish.grizzly.ssl.SSLContextConfigurator$GenericStoreException: java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.createSSLContext(SSLContextConfigurator.java:535)
        at onl.netfishers.netshot.RestService.run(RestService.java:340)
Caused by: java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
        at java.security.KeyStore.load(Unknown Source)
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.loadBytes(SSLContextConfigurator.java:668)
        at org.glassfish.grizzly.ssl.SSLContextConfigurator.createSSLContext(SSLContextConfigurator.java:500)
        ... 1 common frames omitted

I don't know how to make netshot trust the certificate.

Please advice

thanks

**Comment by SCadilhac** [comment]
Please Indicate at least the Netshot release version, and JRE type and version (`java -version`).
