### ISSUE TITLE
Checkpoint GAIA snapshot doesn't work anymore

### ISSUE THREAD

**Issue by RollerOne** [netfishers-onl/Netshot#95]
Hi M Cadillac, 
I like your soft as i deploy it everywhere i work

Here is the isssu 

2021-01-27 09:38:41,596 ERROR [QuartzScheduler_Worker-5] TakeSnapshotTask: **Error while taking the snapshot.
javax.script.ScriptException: Invalid Checkpoint backup status in <eval> at line number 326 at column number 3**
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:392)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:190)
        at onl.netfishers.netshot.device.script.SnapshotCliScript.run(SnapshotCliScript.java:77)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:237)
        at onl.netfishers.netshot.device.script.CliScript.connectRun(CliScript.java:192)
        at onl.netfishers.netshot.work.tasks.TakeSnapshotTask.run(TakeSnapshotTask.java:200)
        at onl.netfishers.netshot.work.TaskJob.execute(TaskJob.java:90)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: jdk.nashorn.internal.runtime.ECMAException: Invalid Checkpoint backup status
        at jdk.nashorn.internal.runtime.ECMAException.create(ECMAException.java:113)
        at jdk.nashorn.internal.scripts.Script$Recompilation$164$4047AAAA$\^eval\_.snapshot(<eval>:326)
        at jdk.nashorn.internal.scripts.Script$Recompilation$223$795AAAA$\^eval\_._connect(<eval>:473)
        at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:645)
        at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
        at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
        at jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:199)
        at jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:386)
        ... 8 common frames omitted

I already have issues about the snapshot from checkpoint but already solved it changing rights one year ago.
Is there a way to find a solution to this issu without upgrading ?

My version is 0.13.0. If i migrate to 0.15.2 will i need to migrate to intermediate version ?
I don't want to lose some drivers and specific conf. 

Regards
YL

**Comment by SCadilhac** [comment]
The driver expects `show backup status` to return `backup succeeded`. What's the result on your device?

As for upgrade steps, you can refer to this page: https://github.com/netfishers-onl/Netshot/wiki/Updating-Netshot-to-a-new-version
No specific action is required to upgrade from 0.13.0 to 0.15.2.

**Comment by RollerOne** [comment]
thank you for your respond.
