### ISSUE TITLE
New install dont work

### ISSUE THREAD

**Issue by jforasetto** [netfishers-onl/Netshot#96]
Hello i just done my first install of netshot 0.15.2,

I have enable the debug level "ALL"

i got this following error 

**from netshot.log**

`2021-02-02 11:40:33,404 ERROR [REST Service] RestService: Fatal error with the REST service.
org.glassfish.grizzly.ssl.SSLContextConfigurator$GenericStoreException: java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
	at org.glassfish.grizzly.ssl.SSLContextConfigurator.createSSLContext(SSLContextConfigurator.java:511)
	at onl.netfishers.netshot.RestService.run(RestService.java:381)
Caused by: java.io.IOException: error constructing MAC: java.lang.SecurityException: JCE cannot authenticate the provider BC
	at org.bouncycastle.jcajce.provider.keystore.pkcs12.PKCS12KeyStoreSpi.engineLoad(Unknown Source)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.glassfish.grizzly.ssl.SSLContextConfigurator.loadBytes(SSLContextConfigurator.java:644)
	at org.glassfish.grizzly.ssl.SSLContextConfigurator.createSSLContext(SSLContextConfigurator.java:476)
	... 1 common frames omitted
2021-02-02 11:52:36,099 WARN  [main] Netshot: Audit information will be logged to /var/log/netshot/audit.log.
2021-02-02 11:52:36,100 INFO  [main] Netshot: Enabling BouncyCastle security.
2021-02-02 11:52:36,232 INFO  [main] Netshot: Initializing the task manager.
2021-02-02 11:52:36,262 INFO  [main] StdSchedulerFactory: Using default implementation for ThreadExecutor
2021-02-02 11:52:36,280 INFO  [main] SchedulerSignalerImpl: Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2021-02-02 11:52:36,281 INFO  [main] QuartzScheduler: Quartz Scheduler v.2.3.2 created.
2021-02-02 11:52:36,281 INFO  [main] RAMJobStore: RAMJobStore initialized.
2021-02-02 11:52:36,282 INFO  [main] QuartzScheduler: Scheduler meta-data: Quartz Scheduler (v2.3.2) 'QuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-02-02 11:52:36,282 INFO  [main] StdSchedulerFactory: Quartz scheduler 'QuartzScheduler' initialized from an externally provided properties instance.
2021-02-02 11:52:36,282 INFO  [main] StdSchedulerFactory: Quartz scheduler version: 2.3.2
2021-02-02 11:52:36,282 INFO  [main] QuartzScheduler: Scheduler QuartzScheduler_$_NON_CLUSTERED started.
2021-02-02 11:52:36,282 INFO  [main] Netshot: Updating the database schema, if necessary.
2021-02-02 11:52:36,293 DEBUG [QuartzScheduler_QuartzSchedulerThread] QuartzSchedulerThread: batch acquisition of 0 triggers
2021-02-02 11:52:36,530 DEBUG [main] ClassLoaderResourceAccessor: Opening jar:file:/usr/local/netshot/netshot.jar!/META-INF/MANIFEST.MF as META-INF/MANIFEST.MF
`

I run the install on Debian 10

$ Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Java version**  

$ java -version
java version "1.8.0_281"
Java(TM) SE Runtime Environment (build 1.8.0_281-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.281-b09, mixed mode)

**Mysql Version** 

mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Access to the DB mariadb ok for user netshot**

$mysql -u netshot -p -Dnetshot01
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 66
Server version: 10.3.27-MariaDB-0+deb10u1 Debian 10

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [netshot01]> exit
Bye

my right in /usr/local/netshot/

drwxr-xr-x 2 netshot root     4096 févr.  2 10:50 drivers
-rw-r--r-- 1 netshot root 66232474 févr.  2 10:49 netshot.jar
-rw-r--r-- 1 netshot nety  4311 févr.  2 10:48 netshot.pfx

Thx in advance for your help !
BR.
Julien

**Comment by SCadilhac** [comment]
Can you try with the OpenJDK 11 JRE (Debian package) instead of Oracle Java 8?

**Comment by jforasetto** [comment]
Perfect that work sry for my $!$*$ issue ! 

![image](https://user-images.githubusercontent.com/51237397/106755684-b10ed480-662e-11eb-9722-220049b50e4c.png)

i try with oracle java 8 who is recommanded in your wiki sry :(.

**Action done :**
i removed my jdk8
$ sudo update-alternatives --remove "java" "/usr/lib/jvm/jdk1.8.0_281/bin/java"
$ sudo update-alternatives --remove "javac" "/usr/lib/jvm/jdk1.8.0_281/bin/javac"
$ sudo update-alternatives --remove "javaws" "/usr/lib/jvm/jdk1.8.0_281/jre/bin/javaws"

$ sudo rm -r /usr/lib/jvm/jdk1.8.0_281

Install default-jre & jdk 

$ sudo apt update
$ sudo apt install default-jre default-jdk

**New version of jdk used for Debian 10:** 

$ java -version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

Thanks again for your advice.

BR.
Julien.
