### ISSUE TITLE
Compatibility with MySQL/MariaDB ?

### ISSUE THREAD

**Issue by kedare** [netfishers-onl/Netshot#98]
Hello.

Is the project still compatible with MySQL/MariaDB ? I tried with both, and in both case I had errors during database initialization complaining about maximum row size like this one

```
2021-02-11 11:25:58,980 ERROR [main] ChangeSet: Change Set migration/netshot0.xml::0.5.2_1::netshot (generated) failed.  Error: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes 
storage overhead, check the manual. You have to change some columns to TEXT or BLOBs [Failed SQL: CREATE TABLE netshot.device_credential_set (dtype VARCHAR(31) NOT NULL, id BIGINT AUTO_INCREMENT NOT NULL, change_date datetime NULL, name VARCHAR(255) NULL, version INT NOT NULL, community VARCHAR(255) NULL, password VARCHAR(255) NULL, super_password VARCHAR(255) NULL, username VARCHAR(255) NULL, private_key VARCHAR(10000) NULL, public_key VARCHAR(10000) NULL, mgmt_domain BI
GINT NULL, CONSTRAINT PK_DEVICE_CREDENTIAL_SET PRIMARY KEY (id), UNIQUE (name))]                            
2021-02-11 11:25:59,000 ERROR [main] Database: Unable to connect to the database (for the initial schema update)
liquibase.exception.MigrationFailedException: Migration failed for change set migration/netshot0.xml::0.5.2_1::netshot (generated):
     Reason: liquibase.exception.DatabaseException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT 
or BLOBs [Failed SQL: CREATE TABLE netshot.device_credential_set (dtype VARCHAR(31) NOT NULL, id BIGINT AUTO_INCREMENT NOT NULL, change_date datetime NULL, name VARCHAR(255) NULL, version INT NOT NULL, community VARCHAR(255) NULL, passwor
d VARCHAR(255) NULL, super_password VARCHAR(255) NULL, username VARCHAR(255) NULL, private_key VARCHAR(10000) NULL, public_key VARCHAR(10000) NULL, mgmt_domain BIGINT NULL, CONSTRAINT PK_DEVICE_CREDENTIAL_SET PRIMARY KEY (id), UNIQUE (nam
e))]                               
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)                                                                                                                                                                          
        at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)                             
        at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)   
        at liquibase.Liquibase.update(Liquibase.java:202)                                                              
        at liquibase.Liquibase.update(Liquibase.java:179)                                                              
        at onl.netfishers.netshot.Database.update(Database.java:598)
        at onl.netfishers.netshot.Netshot.main(Netshot.java:455)
Caused by: liquibase.exception.DatabaseException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or
 BLOBs [Failed SQL: CREATE TABLE netshot.device_credential_set (dtype VARCHAR(31) NOT NULL, id BIGINT AUTO_INCREMENT NOT NULL, change_date datetime NULL, name VARCHAR(255) NULL, version INT NOT NULL, community VARCHAR(255) NULL, password 
VARCHAR(255) NULL, super_password VARCHAR(255) NULL, username VARCHAR(255) NULL, private_key VARCHAR(10000) NULL, public_key VARCHAR(10000) NULL, mgmt_domain BIGINT NULL, CONSTRAINT PK_DEVICE_CREDENTIAL_SET PRIMARY KEY (id), UNIQUE (name)
)]
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
        at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
        at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
        at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
        at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
        ... 6 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOB
s
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
        ... 11 common frames omitted
```

Thanks

**Comment by SCadilhac** [comment]
I recommend using PostgreSQL.
MySQL/MariaDB 5.5-7 should work.
See also a21c918f3ef83dd25b027df52f54640780ccff4f for Netshot 0.16.0

**Comment by PatrickDenis** [comment]
It seams to be same error I'm Having .
